
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComingSoonView(object):
    def setupUi(self, Dialog_Error_Login):
        Dialog_Error_Login.setObjectName("Dialog_Error_Login")
        Dialog_Error_Login.setWindowModality(QtCore.Qt.NonModal)
        Dialog_Error_Login.resize(421, 174)
        Dialog_Error_Login.setMinimumSize(QtCore.QSize(421, 174))
        Dialog_Error_Login.setMaximumSize(QtCore.QSize(421, 174))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Error_Login.setWindowIcon(icon)
        Dialog_Error_Login.setAccessibleName("")
        Dialog_Error_Login.setAccessibleDescription("")
        Dialog_Error_Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog_Error_Login.setSizeGripEnabled(False)
        Dialog_Error_Login.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Error_Login)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog_Error_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/resources/Error and Allert/Allert_Giallo.png"))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog_Error_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog_Error_Login)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton_OK = QtWidgets.QPushButton(Dialog_Error_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_OK.sizePolicy().hasHeightForWidth())
        self.pushButton_OK.setSizePolicy(sizePolicy)
        self.pushButton_OK.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.verticalLayout.addWidget(self.pushButton_OK)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog_Error_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Error_Login)

    def retranslateUi(self, Dialog_Error_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Error_Login.setWindowTitle(_translate("Dialog_Error_Login", "Informazione"))
        self.label_2.setText(_translate("Dialog_Error_Login", "COMING SOON!"))
        self.label_3.setText(_translate("Dialog_Error_Login", "Funzione non ancora disponibile. \n"
"Attendere aggiornamenti!"))
        self.pushButton_OK.setText(_translate("Dialog_Error_Login", "OK"))
        self.pushButton_OK.setShortcut(_translate("Dialog_Error_Login", "Return"))

