from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnagraficheView(object):
    def setupUi(self, Anagrafiche_Window):
        Anagrafiche_Window.setObjectName("Anagrafiche_Window")
        Anagrafiche_Window.setWindowTitle("Anagrafiche")
        Anagrafiche_Window.resize(1400, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Anagrafiche_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Anagrafiche_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setContentsMargins(3, -1, 3, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_Anagrafiche = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Anagrafiche.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Anagrafiche.sizePolicy().hasHeightForWidth())
        self.tabWidget_Anagrafiche.setSizePolicy(sizePolicy)
        self.tabWidget_Anagrafiche.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_Anagrafiche.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_Anagrafiche.setFont(font)
        self.tabWidget_Anagrafiche.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget_Anagrafiche.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_Anagrafiche.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_Anagrafiche.setDocumentMode(False)
        self.tabWidget_Anagrafiche.setTabBarAutoHide(False)
        self.tabWidget_Anagrafiche.setObjectName("tabWidget_Anagrafiche")
        self.Layout_clienti = QtWidgets.QWidget()
        self.Layout_clienti.setObjectName("Layout_clienti")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Layout_clienti)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineE_infoCheckin_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineE_infoCheckin_Cliente.sizePolicy().hasHeightForWidth())
        self.lineE_infoCheckin_Cliente.setSizePolicy(sizePolicy)
        self.lineE_infoCheckin_Cliente.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_infoCheckin_Cliente.setFont(font)
        self.lineE_infoCheckin_Cliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineE_infoCheckin_Cliente.setObjectName("lineE_infoCheckin_Cliente")
        self.gridLayout_7.addWidget(self.lineE_infoCheckin_Cliente, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pB_aggiungi_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_aggiungi_Cliente)
        self.pB_aggiungi_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_aggiungi_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_aggiungi_Cliente.setObjectName("pB_aggiungi_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_aggiungi_Cliente)
        self.pB_modifica_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_modifica_Cliente)
        self.pB_modifica_Cliente.setEnabled(False)
        self.pB_modifica_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_modifica_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_modifica_Cliente.setObjectName("pB_modifica_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_modifica_Cliente)
        self.pB_elimina_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_elimina_Cliente)
        self.pB_elimina_Cliente.setEnabled(False)
        self.pB_elimina_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_elimina_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_elimina_Cliente.setObjectName("pB_elimina_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_elimina_Cliente)
        self.pB_ricerca_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_ricerca_Cliente)
        self.pB_ricerca_Cliente.setEnabled(False)
        self.pB_ricerca_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_ricerca_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_ricerca_Cliente.setObjectName("pB_ricerca_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_ricerca_Cliente)
        self.pB_salva_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_salva_Cliente)
        self.pB_salva_Cliente.setEnabled(False)
        self.pB_salva_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_salva_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_salva_Cliente.setObjectName("pB_salva_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_salva_Cliente)
        self.pB_annulla_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_annulla_Cliente)
        self.pB_annulla_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_annulla_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_annulla_Cliente.setDefault(False)
        self.pB_annulla_Cliente.setFlat(False)
        self.pB_annulla_Cliente.setObjectName("pB_annulla_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_annulla_Cliente)
        self.pB_creaPDF_Cliente = QtWidgets.QPushButton(self.Layout_clienti)
        self.buttonFont(self.pB_creaPDF_Cliente)
        self.pB_creaPDF_Cliente.setEnabled(False)
        self.pB_creaPDF_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_creaPDF_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_creaPDF_Cliente.setObjectName("pB_creaPDF_Cliente")
        self.horizontalLayout_2.addWidget(self.pB_creaPDF_Cliente)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tableWidget_Clienti = QtWidgets.QTableWidget(self.Layout_clienti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Clienti.sizePolicy().hasHeightForWidth())
        self.tableWidget_Clienti.setSizePolicy(sizePolicy)
        self.tableFont(self.tableWidget_Clienti)
        self.tableWidget_Clienti.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_Clienti.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_Clienti.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Clienti.setAlternatingRowColors(True)
        self.tableWidget_Clienti.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Clienti.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_Clienti.setObjectName("tableWidget_Anagrafiche")
        self.tableWidget_Clienti.setColumnCount(22)
        self.tableWidget_Clienti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Clienti.setHorizontalHeaderItem(21, item)
        self.tableWidget_Clienti.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Clienti.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_Clienti.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tableWidget_Clienti, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dE_nascita_Cliente = QtWidgets.QDateEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dE_nascita_Cliente.setFont(font)
        self.dE_nascita_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.dE_nascita_Cliente.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dE_nascita_Cliente.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dE_nascita_Cliente.setCalendarPopup(True)
        self.dE_nascita_Cliente.setObjectName("dE_nascita_Cliente")
        self.gridLayout.addWidget(self.dE_nascita_Cliente, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_17)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.lineE_cellulare_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cellulare_Cliente.setFont(font)
        self.lineE_cellulare_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cellulare_Cliente.setObjectName("lineE_cellulare_Cliente")
        self.gridLayout.addWidget(self.lineE_cellulare_Cliente, 6, 3, 1, 1)
        self.lineE_numeroDoc_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_numeroDoc_Cliente.setFont(font)
        self.lineE_numeroDoc_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_numeroDoc_Cliente.setObjectName("lineE_numeroDoc_Cliente")
        self.gridLayout.addWidget(self.lineE_numeroDoc_Cliente, 6, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.lineE_nazione_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_nazione_Cliente.setFont(font)
        self.lineE_nazione_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_nazione_Cliente.setObjectName("lineE_nazione_Cliente")
        self.gridLayout.addWidget(self.lineE_nazione_Cliente, 3, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_21)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 4, 1, 1)
        self.lineE_email_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_email_Cliente.setFont(font)
        self.lineE_email_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_email_Cliente.setObjectName("lineE_email_Cliente")
        self.gridLayout.addWidget(self.lineE_email_Cliente, 7, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineE_cf_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cf_Cliente.setFont(font)
        self.lineE_cf_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cf_Cliente.setObjectName("lineE_cf_Cliente")
        self.horizontalLayout.addWidget(self.lineE_cf_Cliente)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_7)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_9)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineE_provincia_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_provincia_Cliente.setFont(font)
        self.lineE_provincia_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_provincia_Cliente.setObjectName("lineE_provincia_Cliente")
        self.gridLayout.addWidget(self.lineE_provincia_Cliente, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.cB_sesso_Cliente = QtWidgets.QComboBox(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_sesso_Cliente.setFont(font)
        self.cB_sesso_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_sesso_Cliente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cB_sesso_Cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cB_sesso_Cliente.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cB_sesso_Cliente.setEditable(False)
        self.cB_sesso_Cliente.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cB_sesso_Cliente.setDuplicatesEnabled(False)
        self.cB_sesso_Cliente.setFrame(True)
        self.cB_sesso_Cliente.setObjectName("cB_sesso_Cliente")
        self.cB_sesso_Cliente.setEditable(True)
        self.cB_sesso_Cliente.addItem("")
        self.cB_sesso_Cliente.addItem("")
        self.cB_sesso_Cliente.addItem("")
        self.cB_sesso_Cliente.addItem("")
        line_edit = self.cB_sesso_Cliente.lineEdit()
        line_edit.setAlignment(QtCore.Qt.AlignCenter)
        line_edit.setReadOnly(True)
        self.gridLayout.addWidget(self.cB_sesso_Cliente, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_6)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.lineE_cap_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cap_Cliente.setFont(font)
        self.lineE_cap_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cap_Cliente.setObjectName("lineE_cap_Cliente")
        self.gridLayout.addWidget(self.lineE_cap_Cliente, 2, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_20)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_18)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 2, 1, 1)
        self.lineE_enteRilascio_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_enteRilascio_Cliente.setFont(font)
        self.lineE_enteRilascio_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_enteRilascio_Cliente.setPlaceholderText("")
        self.lineE_enteRilascio_Cliente.setObjectName("lineE_enteRilascio_Cliente")
        self.gridLayout.addWidget(self.lineE_enteRilascio_Cliente, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_10)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_5)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_8)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_16)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.lineE_via_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_via_Cliente.setFont(font)
        self.lineE_via_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_via_Cliente.setObjectName("lineE_via_Cliente")
        self.gridLayout.addWidget(self.lineE_via_Cliente, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_13)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 2, 1, 1)
        self.lineE_telefono_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_telefono_Cliente.setFont(font)
        self.lineE_telefono_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_telefono_Cliente.setObjectName("lineE_telefono_Cliente")
        self.gridLayout.addWidget(self.lineE_telefono_Cliente, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_15)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 4, 1, 1)
        self.cB_documento_Cliente = QtWidgets.QComboBox(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_documento_Cliente.setFont(font)
        self.cB_documento_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_documento_Cliente.setObjectName("cB_documento_Cliente")
        self.cB_documento_Cliente.setEditable(True)
        self.cB_documento_Cliente.addItem("")
        self.cB_documento_Cliente.addItem("")
        self.cB_documento_Cliente.addItem("")
        self.cB_documento_Cliente.addItem("")
        line_edit = self.cB_documento_Cliente.lineEdit()
        line_edit.setAlignment(QtCore.Qt.AlignCenter)
        line_edit.setReadOnly(True)
        self.gridLayout.addWidget(self.cB_documento_Cliente, 5, 1, 1, 1)
        self.dE_dataScadenza_Cliente = QtWidgets.QDateEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dE_dataScadenza_Cliente.setFont(font)
        self.dE_dataScadenza_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.dE_dataScadenza_Cliente.setCalendarPopup(True)
        self.dE_dataScadenza_Cliente.setObjectName("dE_dataScadenza_Cliente")
        self.gridLayout.addWidget(self.dE_dataScadenza_Cliente, 5, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_11)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_12)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 4, 1, 1)
        self.dE_dataRilascio_Cliente = QtWidgets.QDateEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dE_dataRilascio_Cliente.setFont(font)
        self.dE_dataRilascio_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.dE_dataRilascio_Cliente.setCalendarPopup(True)
        self.dE_dataRilascio_Cliente.setObjectName("dE_dataRilascio_Cliente")
        self.gridLayout.addWidget(self.dE_dataRilascio_Cliente, 5, 3, 1, 1)
        self.lineE_cognome_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cognome_Cliente.setFont(font)
        self.lineE_cognome_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cognome_Cliente.setObjectName("lineE_cognome_Cliente")
        self.gridLayout.addWidget(self.lineE_cognome_Cliente, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_22)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 7, 2, 1, 1)
        self.cB_modalitaPag_Cliente = QtWidgets.QComboBox(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_modalitaPag_Cliente.setFont(font)
        self.cB_modalitaPag_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_modalitaPag_Cliente.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cB_modalitaPag_Cliente.setObjectName("cB_modalitaPag_Cliente")
        self.cB_modalitaPag_Cliente.setEditable(True)
        self.cB_modalitaPag_Cliente.addItem("")
        self.cB_modalitaPag_Cliente.addItem("")
        self.cB_modalitaPag_Cliente.addItem("")
        self.cB_modalitaPag_Cliente.addItem("")
        line_edit = self.cB_modalitaPag_Cliente.lineEdit()
        line_edit.setAlignment(QtCore.Qt.AlignCenter)
        line_edit.setReadOnly(True)
        self.gridLayout.addWidget(self.cB_modalitaPag_Cliente, 7, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Layout_clienti)
        self.labelFont(self.label_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineE_nome_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        self.lineE_nome_Cliente.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_nome_Cliente.setFont(font)
        self.lineE_nome_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_nome_Cliente.setObjectName("lineE_nome_Cliente")
        self.gridLayout.addWidget(self.lineE_nome_Cliente, 0, 1, 1, 1)
        self.lineE_nascita_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_nascita_Cliente.setFont(font)
        self.lineE_nascita_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_nascita_Cliente.setObjectName("lineE_nascita_Cliente")
        self.gridLayout.addWidget(self.lineE_nascita_Cliente, 1, 1, 1, 1)
        self.lineE_residenza_Cliente = QtWidgets.QLineEdit(self.Layout_clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_residenza_Cliente.setFont(font)
        self.lineE_residenza_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_residenza_Cliente.setObjectName("lineE_residenza_Cliente")
        self.gridLayout.addWidget(self.lineE_residenza_Cliente, 1, 6, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(19, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.Layout_clienti, "")
        self.tab_Anag_Fornitori = QtWidgets.QWidget()
        self.tab_Anag_Fornitori.setObjectName("tab_Anag_Fornitori")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Anag_Fornitori)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pB_aggiungi_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_aggiungi_Fornitore)
        self.pB_aggiungi_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_aggiungi_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_aggiungi_Fornitore.setObjectName("pB_aggiungi_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_aggiungi_Fornitore)
        self.pB_modifica_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_modifica_Fornitore)
        self.pB_modifica_Fornitore.setEnabled(False)
        self.pB_modifica_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_modifica_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_modifica_Fornitore.setObjectName("pB_modifica_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_modifica_Fornitore)
        self.pB_elimina_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_elimina_Fornitore)
        self.pB_elimina_Fornitore.setEnabled(False)
        self.pB_elimina_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_elimina_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_elimina_Fornitore.setObjectName("pB_elimina_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_elimina_Fornitore)
        self.pB_ricerca_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_ricerca_Fornitore)
        self.pB_ricerca_Fornitore.setEnabled(False)
        self.pB_ricerca_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_ricerca_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_ricerca_Fornitore.setObjectName("pB_ricerca_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_ricerca_Fornitore)
        self.pB_salva_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_salva_Fornitore)
        self.pB_salva_Fornitore.setEnabled(False)
        self.pB_salva_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_salva_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_salva_Fornitore.setObjectName("pB_salva_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_salva_Fornitore)
        self.pB_annulla_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_annulla_Fornitore)
        self.pB_annulla_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_annulla_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_annulla_Fornitore.setDefault(False)
        self.pB_annulla_Fornitore.setFlat(False)
        self.pB_annulla_Fornitore.setObjectName("pB_annulla_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_annulla_Fornitore)
        self.pB_creaPDF_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.buttonFont(self.pB_creaPDF_Fornitore)
        self.pB_creaPDF_Fornitore.setEnabled(False)
        self.pB_creaPDF_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_creaPDF_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_creaPDF_Fornitore.setObjectName("pB_creaPDF_Fornitore")
        self.horizontalLayout_3.addWidget(self.pB_creaPDF_Fornitore)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tableWidget_Fornitore = QtWidgets.QTableWidget(self.tab_Anag_Fornitori)
        self.tableFont(self.tableWidget_Fornitore)
        self.tableWidget_Fornitore.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Fornitore.setAlternatingRowColors(True)
        self.tableWidget_Fornitore.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Fornitore.setObjectName("tableWidget_Fornitore")
        self.tableWidget_Fornitore.setColumnCount(12)
        self.tableWidget_Fornitore.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Fornitore.setHorizontalHeaderItem(11, item)
        self.tableWidget_Fornitore.horizontalHeader().setDefaultSectionSize(183)
        self.tableWidget_Fornitore.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Fornitore.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget_Fornitore, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, 20, 10, 20)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_31 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_31)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 3, 0, 1, 1)
        self.lineE_email_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_email_Fornitore.setFont(font)
        self.lineE_email_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_email_Fornitore.setObjectName("lineE_email_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_email_Fornitore, 3, 1, 1, 1)
        self.lineE_IVA_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_IVA_Fornitore.setFont(font)
        self.lineE_IVA_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_IVA_Fornitore.setObjectName("lineE_IVA_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_IVA_Fornitore, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_25)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_30)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineE_telefonoRif_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_telefonoRif_Fornitore.setFont(font)
        self.lineE_telefonoRif_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_telefonoRif_Fornitore.setObjectName("lineE_telefonoRif_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_telefonoRif_Fornitore, 2, 1, 1, 1)
        self.lineE_fornitura2_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_fornitura2_Fornitore.setFont(font)
        self.lineE_fornitura2_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_fornitura2_Fornitore.setObjectName("lineE_fornitura2_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_fornitura2_Fornitore, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_24)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_28)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_23)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 4, 1, 1)
        self.lineE_telefono_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_telefono_Fornitore.setFont(font)
        self.lineE_telefono_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_telefono_Fornitore.setObjectName("lineE_telefono_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_telefono_Fornitore, 2, 5, 1, 1)
        self.cB_modalitaPag_Fornitore = QtWidgets.QComboBox(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_modalitaPag_Fornitore.setFont(font)
        self.cB_modalitaPag_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_modalitaPag_Fornitore.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cB_modalitaPag_Fornitore.setObjectName("cB_modalitaPag_Fornitore")
        self.cB_modalitaPag_Fornitore.setEditable(True)
        self.cB_modalitaPag_Fornitore.addItem("")
        self.cB_modalitaPag_Fornitore.addItem("")
        self.cB_modalitaPag_Fornitore.addItem("")
        self.cB_modalitaPag_Fornitore.addItem("")
        line_edit = self.cB_modalitaPag_Fornitore.lineEdit()
        line_edit.setAlignment(QtCore.Qt.AlignCenter)
        line_edit.setReadOnly(True)
        self.gridLayout_3.addWidget(self.cB_modalitaPag_Fornitore, 0, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_33)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineE_nome_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_nome_Fornitore.setFont(font)
        self.lineE_nome_Fornitore.setText("")
        self.lineE_nome_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_nome_Fornitore.setObjectName("lineE_nome_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_nome_Fornitore, 0, 1, 1, 1)
        self.lineE_fornitura1_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_fornitura1_Fornitore.setFont(font)
        self.lineE_fornitura1_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_fornitura1_Fornitore.setObjectName("lineE_fornitura1_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_fornitura1_Fornitore, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_27)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 2, 1, 1)
        self.lineE_riferimento_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_riferimento_Fornitore.setFont(font)
        self.lineE_riferimento_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_riferimento_Fornitore.setObjectName("lineE_riferimento_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_riferimento_Fornitore, 1, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_19)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 4, 1, 1)
        self.lineE_indirizzo_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_indirizzo_Fornitore.setFont(font)
        self.lineE_indirizzo_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_indirizzo_Fornitore.setObjectName("lineE_indirizzo_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_indirizzo_Fornitore, 2, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_26)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.labelFont(self.label_29)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 2, 1, 1)
        self.lineE_fax_Fornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_fax_Fornitore.setFont(font)
        self.lineE_fax_Fornitore.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_fax_Fornitore.setObjectName("lineE_fax_Fornitore")
        self.gridLayout_3.addWidget(self.lineE_fax_Fornitore, 3, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.tab_Anag_Fornitori, "")
        self.tab_Anag_Utenti = QtWidgets.QWidget()
        self.tab_Anag_Utenti.setObjectName("tab_Anag_Utenti")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Anag_Utenti)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pB_aggiungi_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_aggiungi_Dipendente)
        self.pB_aggiungi_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_aggiungi_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_aggiungi_Dipendente.setObjectName("pB_aggiungi_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_aggiungi_Dipendente)
        self.pB_modifica_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_modifica_Dipendente)
        self.pB_modifica_Dipendente.setEnabled(False)
        self.pB_modifica_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_modifica_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_modifica_Dipendente.setObjectName("pB_modifica_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_modifica_Dipendente)
        self.pB_elimina_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_elimina_Dipendente)
        self.pB_elimina_Dipendente.setEnabled(False)
        self.pB_elimina_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_elimina_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_elimina_Dipendente.setObjectName("pB_elimina_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_elimina_Dipendente)
        self.pB_ricerca_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_ricerca_Dipendente)
        self.pB_ricerca_Dipendente.setEnabled(False)
        self.pB_ricerca_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_ricerca_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_ricerca_Dipendente.setObjectName("pB_ricerca_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_ricerca_Dipendente)
        self.pB_salva_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_salva_Dipendente)
        self.pB_salva_Dipendente.setEnabled(False)
        self.pB_salva_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_salva_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_salva_Dipendente.setObjectName("pB_salva_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_salva_Dipendente)
        self.pB_annulla_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_annulla_Dipendente)
        self.pB_annulla_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_annulla_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_annulla_Dipendente.setObjectName("pB_annulla_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_annulla_Dipendente)
        self.pB_creaPDF_Dipendente = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.buttonFont(self.pB_creaPDF_Dipendente)
        self.pB_creaPDF_Dipendente.setEnabled(False)
        self.pB_creaPDF_Dipendente.setMinimumSize(QtCore.QSize(180, 40))
        self.pB_creaPDF_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_creaPDF_Dipendente.setObjectName("pB_creaPDF_Dipendente")
        self.horizontalLayout_7.addWidget(self.pB_creaPDF_Dipendente)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_5.setHorizontalSpacing(20)
        self.gridLayout_5.setVerticalSpacing(25)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_42)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.lineE_username_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_username_Dipendente.setFont(font)
        self.lineE_username_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_username_Dipendente.setObjectName("lineE_username_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_username_Dipendente, 0, 1, 1, 1)
        self.lineE_password_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_password_Dipendente.setFont(font)
        self.lineE_password_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_password_Dipendente.setObjectName("lineE_password_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_password_Dipendente, 0, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_43)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 0, 2, 1, 1)
        self.lineE_nome_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_nome_Dipendente.setFont(font)
        self.lineE_nome_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_nome_Dipendente.setObjectName("lineE_nome_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_nome_Dipendente, 0, 5, 1, 1)
        self.lineE_email_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_email_Dipendente.setFont(font)
        self.lineE_email_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_email_Dipendente.setObjectName("lineE_email_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_email_Dipendente, 1, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_46)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 1, 2, 1, 1)
        self.lineE_cognome_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cognome_Dipendente.setFont(font)
        self.lineE_cognome_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cognome_Dipendente.setObjectName("lineE_cognome_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_cognome_Dipendente, 1, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_45)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_44)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 4, 1, 1)
        self.lineE_cellulare_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_cellulare_Dipendente.setFont(font)
        self.lineE_cellulare_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_cellulare_Dipendente.setObjectName("lineE_cellulare_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_cellulare_Dipendente, 1, 5, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_47)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 1, 4, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_48)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 2, 0, 1, 1)
        self.dE_nascita_Dipendente = QtWidgets.QDateEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dE_nascita_Dipendente.setFont(font)
        self.dE_nascita_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.dE_nascita_Dipendente.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dE_nascita_Dipendente.setCalendarPopup(True)
        self.dE_nascita_Dipendente.setObjectName("dE_nascita_Dipendente")
        self.gridLayout_5.addWidget(self.dE_nascita_Dipendente, 2, 1, 1, 1)
        self.lineE_ambito_Dipendente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineE_ambito_Dipendente.setFont(font)
        self.lineE_ambito_Dipendente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineE_ambito_Dipendente.setObjectName("lineE_ambito_Dipendente")
        self.gridLayout_5.addWidget(self.lineE_ambito_Dipendente, 2, 3, 1, 1)
        self.cB_permessi_Dipendente = QtWidgets.QComboBox(self.tab_Anag_Utenti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_permessi_Dipendente.sizePolicy().hasHeightForWidth())
        self.cB_permessi_Dipendente.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_permessi_Dipendente.setFont(font)
        self.cB_permessi_Dipendente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_permessi_Dipendente.setMaxVisibleItems(10)
        self.cB_permessi_Dipendente.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cB_permessi_Dipendente.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cB_permessi_Dipendente.setObjectName("cB_permessi_Dipendente")
        self.cB_permessi_Dipendente.setEditable(True)
        self.cB_permessi_Dipendente.addItem("")
        self.cB_permessi_Dipendente.addItem("")
        self.cB_permessi_Dipendente.addItem("")
        self.cB_permessi_Dipendente.addItem("")
        line_edit = self.cB_permessi_Dipendente.lineEdit()
        line_edit.setAlignment(QtCore.Qt.AlignCenter)
        line_edit.setReadOnly(True)
        self.gridLayout_5.addWidget(self.cB_permessi_Dipendente, 2, 5, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_92)
        self.label_92.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_5.addWidget(self.label_92, 2, 4, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.labelFont(self.label_91)
        self.label_91.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_5.addWidget(self.label_91, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.tableWidget_Dipendente = QtWidgets.QTableWidget(self.tab_Anag_Utenti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Dipendente.sizePolicy().hasHeightForWidth())
        self.tableWidget_Dipendente.setSizePolicy(sizePolicy)
        self.tableFont(self.tableWidget_Dipendente)
        self.tableWidget_Dipendente.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_Dipendente.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tableWidget_Dipendente.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_Dipendente.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_Dipendente.setLineWidth(1)
        self.tableWidget_Dipendente.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_Dipendente.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_Dipendente.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_Dipendente.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Dipendente.setDragEnabled(False)
        self.tableWidget_Dipendente.setAlternatingRowColors(True)
        self.tableWidget_Dipendente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Dipendente.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_Dipendente.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_Dipendente.setShowGrid(True)
        self.tableWidget_Dipendente.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_Dipendente.setObjectName("tableWidget_Dipendente")
        self.tableWidget_Dipendente.setColumnCount(10)
        self.tableWidget_Dipendente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Dipendente.setHorizontalHeaderItem(9, item)
        self.tableWidget_Dipendente.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Dipendente.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_Dipendente.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Dipendente.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_Dipendente.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Dipendente.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.tableWidget_Dipendente, 1, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.tab_Anag_Utenti, "")
        self.gridLayout_6.addWidget(self.tabWidget_Anagrafiche, 0, 0, 1, 1)
        Anagrafiche_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Anagrafiche_Window)
        self.tabWidget_Anagrafiche.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Anagrafiche_Window)
        Anagrafiche_Window.setTabOrder(self.pB_aggiungi_Cliente, self.pB_modifica_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_modifica_Cliente, self.pB_elimina_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_elimina_Cliente, self.pB_ricerca_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_ricerca_Cliente, self.pB_salva_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_salva_Cliente, self.pB_annulla_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_annulla_Cliente, self.pB_creaPDF_Cliente)
        Anagrafiche_Window.setTabOrder(self.pB_creaPDF_Cliente, self.tableWidget_Clienti)
        Anagrafiche_Window.setTabOrder(self.tableWidget_Clienti, self.lineE_nome_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_nome_Cliente, self.lineE_cognome_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_cognome_Cliente, self.cB_sesso_Cliente)
        Anagrafiche_Window.setTabOrder(self.cB_sesso_Cliente, self.lineE_nascita_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_nascita_Cliente, self.dE_nascita_Cliente)
        Anagrafiche_Window.setTabOrder(self.dE_nascita_Cliente, self.lineE_residenza_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_residenza_Cliente, self.lineE_provincia_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_provincia_Cliente, self.lineE_via_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_via_Cliente, self.lineE_cap_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_cap_Cliente, self.lineE_cf_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_cf_Cliente, self.lineE_telefono_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_telefono_Cliente, self.lineE_nazione_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_nazione_Cliente, self.cB_documento_Cliente)
        Anagrafiche_Window.setTabOrder(self.cB_documento_Cliente, self.dE_dataRilascio_Cliente)
        Anagrafiche_Window.setTabOrder(self.dE_dataRilascio_Cliente, self.dE_dataScadenza_Cliente)
        Anagrafiche_Window.setTabOrder(self.dE_dataScadenza_Cliente, self.lineE_enteRilascio_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_enteRilascio_Cliente, self.lineE_cellulare_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_cellulare_Cliente, self.lineE_numeroDoc_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_numeroDoc_Cliente, self.lineE_email_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_email_Cliente, self.cB_modalitaPag_Cliente)
        Anagrafiche_Window.setTabOrder(self.cB_modalitaPag_Cliente, self.lineE_infoCheckin_Cliente)
        Anagrafiche_Window.setTabOrder(self.lineE_infoCheckin_Cliente, self.pB_aggiungi_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_aggiungi_Fornitore, self.pB_modifica_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_modifica_Fornitore, self.pB_elimina_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_elimina_Fornitore, self.pB_ricerca_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_ricerca_Fornitore, self.pB_salva_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_salva_Fornitore, self.pB_annulla_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_annulla_Fornitore, self.pB_creaPDF_Fornitore)
        Anagrafiche_Window.setTabOrder(self.pB_creaPDF_Fornitore, self.tableWidget_Fornitore)
        Anagrafiche_Window.setTabOrder(self.tableWidget_Fornitore, self.lineE_nome_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_nome_Fornitore, self.lineE_fornitura1_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_fornitura1_Fornitore, self.cB_modalitaPag_Fornitore)
        Anagrafiche_Window.setTabOrder(self.cB_modalitaPag_Fornitore, self.lineE_fornitura2_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_fornitura2_Fornitore, self.lineE_IVA_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_IVA_Fornitore, self.lineE_riferimento_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_riferimento_Fornitore, self.lineE_telefonoRif_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_telefonoRif_Fornitore, self.lineE_indirizzo_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_indirizzo_Fornitore, self.lineE_telefono_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_telefono_Fornitore, self.lineE_email_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_email_Fornitore, self.lineE_fax_Fornitore)
        Anagrafiche_Window.setTabOrder(self.lineE_fax_Fornitore, self.pB_aggiungi_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_aggiungi_Dipendente, self.pB_modifica_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_modifica_Dipendente, self.pB_elimina_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_elimina_Dipendente, self.pB_ricerca_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_ricerca_Dipendente, self.pB_salva_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_salva_Dipendente, self.pB_annulla_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_annulla_Dipendente, self.pB_creaPDF_Dipendente)
        Anagrafiche_Window.setTabOrder(self.pB_creaPDF_Dipendente, self.tableWidget_Dipendente)
        Anagrafiche_Window.setTabOrder(self.tableWidget_Dipendente, self.lineE_username_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_username_Dipendente, self.lineE_password_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_password_Dipendente, self.lineE_nome_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_nome_Dipendente, self.lineE_cognome_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_cognome_Dipendente, self.lineE_email_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_email_Dipendente, self.lineE_cellulare_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_cellulare_Dipendente, self.dE_nascita_Dipendente)
        Anagrafiche_Window.setTabOrder(self.dE_nascita_Dipendente, self.lineE_ambito_Dipendente)
        Anagrafiche_Window.setTabOrder(self.lineE_ambito_Dipendente, self.cB_permessi_Dipendente)
        Anagrafiche_Window.setTabOrder(self.cB_permessi_Dipendente, self.tabWidget_Anagrafiche)

    def labelFont(self, label):
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        label.setFont(font)

    def buttonFont(self, button):
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        button.setFont(font)

    def tableFont(self, table):
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        table.setFont(font)
        table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)


    def retranslateUi(self, Anagrafiche_Window):
        _translate = QtCore.QCoreApplication.translate
        Anagrafiche_Window.setWindowTitle(_translate("Anagrafiche_Window", "Anagrafiche"))
        self.pB_aggiungi_Cliente.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.pB_modifica_Cliente.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.pB_elimina_Cliente.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.pB_ricerca_Cliente.setText(_translate("Anagrafiche_Window", "Ricerca"))
        self.pB_salva_Cliente.setText(_translate("Anagrafiche_Window", "Salva"))
        self.pB_annulla_Cliente.setText(_translate("Anagrafiche_Window", "Annulla"))
        self.pB_creaPDF_Cliente.setText(_translate("Anagrafiche_Window", "CreaPDF"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Nome"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Cognome"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Sesso"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "Data di Nascita"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "Luogo di Nascita"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "Luogo di Residenza"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "Provincia di Residenza"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "Via di Residenza"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "CAP"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(10)
        item.setText(_translate("Anagrafiche_Window", "Codice Fiscale"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(11)
        item.setText(_translate("Anagrafiche_Window", "Nazione"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(12)
        item.setText(_translate("Anagrafiche_Window", "Telefono"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(13)
        item.setText(_translate("Anagrafiche_Window", "Cellulare"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(14)
        item.setText(_translate("Anagrafiche_Window", "Email"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(15)
        item.setText(_translate("Anagrafiche_Window", "Tipo Documento"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(16)
        item.setText(_translate("Anagrafiche_Window", "Numero Documento"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(17)
        item.setText(_translate("Anagrafiche_Window", "Ente di Rilascio"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(18)
        item.setText(_translate("Anagrafiche_Window", "Data Rilascio"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(19)
        item.setText(_translate("Anagrafiche_Window", "Data Scadenza"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(20)
        item.setText(_translate("Anagrafiche_Window", "Modalità di Pagamento"))
        item = self.tableWidget_Clienti.horizontalHeaderItem(21)
        item.setText(_translate("Anagrafiche_Window", "Info CheckIn"))
        self.label_14.setText(_translate("Anagrafiche_Window", "Info \n"
"CheckIn"))
        self.dE_nascita_Cliente.setDisplayFormat(_translate("Anagrafiche_Window", "dd/MM/yyyy"))
        self.label_17.setText(_translate("Anagrafiche_Window", "Cellulare:"))
        self.label.setText(_translate("Anagrafiche_Window", "Codice fiscale:"))
        self.label_21.setText(_translate("Anagrafiche_Window", "Nazione:"))
        self.label_7.setText(_translate("Anagrafiche_Window", "Residente a:"))
        self.label_9.setText(_translate("Anagrafiche_Window", "Provincia:"))
        self.label_4.setText(_translate("Anagrafiche_Window", "Sesso:"))
        self.cB_sesso_Cliente.setProperty("placeholderText", _translate("Anagrafiche_Window", "Genere"))
        self.cB_sesso_Cliente.setItemText(0, _translate("Anagrafiche_Window", ""))
        self.cB_sesso_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Maschio"))
        self.cB_sesso_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Femmina"))
        self.cB_sesso_Cliente.setItemText(3, _translate("Anagrafiche_Window", "Altro"))
        self.label_6.setText(_translate("Anagrafiche_Window", "Data di nascita:"))
        self.label_20.setText(_translate("Anagrafiche_Window", "Via:"))
        self.label_18.setText(_translate("Anagrafiche_Window", "Telefono:"))
        self.label_10.setText(_translate("Anagrafiche_Window", "E-Mail:"))
        self.label_5.setText(_translate("Anagrafiche_Window", "Luogo di nascita:"))
        self.label_8.setText(_translate("Anagrafiche_Window", "CAP:"))
        self.label_16.setText(_translate("Anagrafiche_Window", "Rilasciato da: "))
        self.label_13.setText(_translate("Anagrafiche_Window", "Rilasciato il:"))
        self.label_15.setText(_translate("Anagrafiche_Window", "Scandenza:"))
        self.cB_documento_Cliente.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli Documento"))
        self.cB_documento_Cliente.setItemText(0, _translate("Anagrafiche_Window", ""))
        self.cB_documento_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Carta d\'Identità"))
        self.cB_documento_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Patente"))
        self.cB_documento_Cliente.setItemText(3, _translate("Anagrafiche_Window", "Passaporto"))
        self.label_11.setText(_translate("Anagrafiche_Window", "Tipo documeto:"))
        self.label_12.setText(_translate("Anagrafiche_Window", "N° documento:"))
        self.label_2.setText(_translate("Anagrafiche_Window", "Cognome:"))
        self.label_22.setText(_translate("Anagrafiche_Window", "Modalità pagamento:"))
        self.cB_modalitaPag_Cliente.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli una modalità"))
        self.cB_modalitaPag_Cliente.setItemText(0, _translate("Anagrafiche_Window", ""))
        self.cB_modalitaPag_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Assegno"))
        self.cB_modalitaPag_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Carta"))
        self.cB_modalitaPag_Cliente.setItemText(3, _translate("Anagrafiche_Window", "Contanti"))
        self.label_3.setText(_translate("Anagrafiche_Window", "Nome:"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.Layout_clienti), _translate("Anagrafiche_Window", "Clienti"))
        self.pB_aggiungi_Fornitore.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.pB_modifica_Fornitore.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.pB_elimina_Fornitore.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.pB_ricerca_Fornitore.setText(_translate("Anagrafiche_Window", "Ricerca"))
        self.pB_salva_Fornitore.setText(_translate("Anagrafiche_Window", "Salva"))
        self.pB_annulla_Fornitore.setText(_translate("Anagrafiche_Window", "Annulla"))
        self.pB_creaPDF_Fornitore.setText(_translate("Anagrafiche_Window", "CreaPDF"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Nome Fornitore"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Tipo Fornitura 1"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Tipo Fornitura 2"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "Partita IVA"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "Riferimento"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "Telefono Riferimento"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "Indirizzo"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "Telefono"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "E-Mail"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(10)
        item.setText(_translate("Anagrafiche_Window", "Modalità di Pagamento"))
        item = self.tableWidget_Fornitore.horizontalHeaderItem(11)
        item.setText(_translate("Anagrafiche_Window", "Fax"))
        self.label_31.setText(_translate("Anagrafiche_Window", "E-Mail:"))
        self.label_25.setText(_translate("Anagrafiche_Window", "Telefono rif. :"))
        self.label_30.setText(_translate("Anagrafiche_Window", "Tipo fornitura 2:"))
        self.label_24.setText(_translate("Anagrafiche_Window", "Partita IVA:"))
        self.label_28.setText(_translate("Anagrafiche_Window", "Telefono:"))
        self.label_23.setText(_translate("Anagrafiche_Window", "Modalità pagamento:"))
        self.cB_modalitaPag_Fornitore.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli una modalità"))
        self.cB_modalitaPag_Fornitore.setItemText(0, _translate("Anagrafiche_Window", ""))
        self.cB_modalitaPag_Fornitore.setItemText(1, _translate("Anagrafiche_Window", "Assegno"))
        self.cB_modalitaPag_Fornitore.setItemText(2, _translate("Anagrafiche_Window", "Bonifico"))
        self.cB_modalitaPag_Fornitore.setItemText(3, _translate("Anagrafiche_Window", "Contanti"))
        self.label_33.setText(_translate("Anagrafiche_Window", "Nome fornitore:"))
        self.label_27.setText(_translate("Anagrafiche_Window", "Tipo fornitura 1:"))
        self.label_19.setText(_translate("Anagrafiche_Window", "Riferimento:"))
        self.label_26.setText(_translate("Anagrafiche_Window", "Indirizzo:"))
        self.label_29.setText(_translate("Anagrafiche_Window", "Fax:"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.tab_Anag_Fornitori), _translate("Anagrafiche_Window", "Fornitori"))
        self.pB_aggiungi_Dipendente.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.pB_modifica_Dipendente.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.pB_elimina_Dipendente.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.pB_ricerca_Dipendente.setText(_translate("Anagrafiche_Window", "Ricerca"))
        self.pB_salva_Dipendente.setText(_translate("Anagrafiche_Window", "Salva"))
        self.pB_annulla_Dipendente.setText(_translate("Anagrafiche_Window", "Annulla"))
        self.pB_creaPDF_Dipendente.setText(_translate("Anagrafiche_Window", "CreaPDF"))
        self.label_42.setText(_translate("Anagrafiche_Window", "Username:"))
        self.label_43.setText(_translate("Anagrafiche_Window", "Password:"))
        self.label_46.setText(_translate("Anagrafiche_Window", "E-Mail:"))
        self.label_45.setText(_translate("Anagrafiche_Window", "Cognome:"))
        self.label_44.setText(_translate("Anagrafiche_Window", "Nome:"))
        self.label_47.setText(_translate("Anagrafiche_Window", "Cellulare:"))
        self.label_48.setText(_translate("Anagrafiche_Window", "Data di Nascita:"))
        self.cB_permessi_Dipendente.setCurrentText(_translate("Anagrafiche_Window", ""))
        self.cB_permessi_Dipendente.setItemText(0, _translate("Anagrafiche_Window", ""))
        self.cB_permessi_Dipendente.setItemText(1, _translate("Anagrafiche_Window", "Admin"))
        self.cB_permessi_Dipendente.setItemText(2, _translate("Anagrafiche_Window", "Responsabile"))
        self.cB_permessi_Dipendente.setItemText(3, _translate("Anagrafiche_Window", "Dipendente"))
        self.label_92.setText(_translate("Anagrafiche_Window", "Permessi:"))
        self.label_91.setText(_translate("Anagrafiche_Window", "Ambito:"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Nome"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Cognome"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Username"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "Password"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "E-Mail"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "Cellulare"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "Data di Nascita"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "Ambito"))
        item = self.tableWidget_Dipendente.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "Permessi"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.tab_Anag_Utenti), _translate("Anagrafiche_Window", "Dipendenti"))
