from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnagraficheView(object):
    def setupUi(self, Anagrafiche_Window):
        Anagrafiche_Window.setObjectName("Anagrafiche_Window")
        Anagrafiche_Window.resize(1315, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Anagrafiche_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Anagrafiche_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setContentsMargins(3, -1, 3, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_Anagrafiche = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Anagrafiche.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Anagrafiche.sizePolicy().hasHeightForWidth())
        self.tabWidget_Anagrafiche.setSizePolicy(sizePolicy)
        self.tabWidget_Anagrafiche.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_Anagrafiche.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_Anagrafiche.setFont(font)
        self.tabWidget_Anagrafiche.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget_Anagrafiche.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_Anagrafiche.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_Anagrafiche.setDocumentMode(False)
        self.tabWidget_Anagrafiche.setTabBarAutoHide(False)
        self.tabWidget_Anagrafiche.setObjectName("tabWidget_Anagrafiche")
        self.tab_Anag_Clienti = QtWidgets.QWidget()
        self.tab_Anag_Clienti.setObjectName("tab_Anag_Clienti")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Anag_Clienti)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_add_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_add_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_add_Cliente.setFont(font)
        self.PB_add_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_add_Cliente.setObjectName("PB_add_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_add_Cliente)
        self.PB_modifica_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_modifica_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_modifica_Cliente.setFont(font)
        self.PB_modifica_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_modifica_Cliente.setObjectName("PB_modifica_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_modifica_Cliente)
        self.PB_Elimina = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_Elimina.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_Elimina.setFont(font)
        self.PB_Elimina.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_Elimina.setObjectName("PB_Elimina")
        self.horizontalLayout_2.addWidget(self.PB_Elimina)
        self.PB_ricerca_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_ricerca_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_ricerca_Cliente.setFont(font)
        self.PB_ricerca_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_ricerca_Cliente.setObjectName("PB_ricerca_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_ricerca_Cliente)
        self.PB_salva_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_salva_Cliente.setEnabled(True)
        self.PB_salva_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_salva_Cliente.setFont(font)
        self.PB_salva_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_salva_Cliente.setObjectName("PB_salva_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_salva_Cliente)
        self.PB_AnnullaMod_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_AnnullaMod_Cliente.setEnabled(True)
        self.PB_AnnullaMod_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_AnnullaMod_Cliente.setFont(font)
        self.PB_AnnullaMod_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_AnnullaMod_Cliente.setDefault(False)
        self.PB_AnnullaMod_Cliente.setFlat(False)
        self.PB_AnnullaMod_Cliente.setObjectName("PB_AnnullaMod_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_AnnullaMod_Cliente)
        self.PB_CreaPDF_Cliente = QtWidgets.QPushButton(self.tab_Anag_Clienti)
        self.PB_CreaPDF_Cliente.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_CreaPDF_Cliente.setFont(font)
        self.PB_CreaPDF_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_CreaPDF_Cliente.setObjectName("PB_CreaPDF_Cliente")
        self.horizontalLayout_2.addWidget(self.PB_CreaPDF_Cliente)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tableWidget_Anagrafiche = QtWidgets.QTableWidget(self.tab_Anag_Clienti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Anagrafiche.sizePolicy().hasHeightForWidth())
        self.tableWidget_Anagrafiche.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Anagrafiche.setFont(font)
        self.tableWidget_Anagrafiche.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget_Anagrafiche.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_Anagrafiche.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Anagrafiche.setAlternatingRowColors(True)
        self.tableWidget_Anagrafiche.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Anagrafiche.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Anagrafiche.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_Anagrafiche.setObjectName("tableWidget_Anagrafiche")
        self.tableWidget_Anagrafiche.setColumnCount(22)
        self.tableWidget_Anagrafiche.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Anagrafiche.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 19, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 20, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_Anagrafiche.setItem(0, 21, item)
        self.tableWidget_Anagrafiche.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Anagrafiche.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_Anagrafiche.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tableWidget_Anagrafiche, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit_nascita_Clienti = QtWidgets.QDateEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_nascita_Clienti.setFont(font)
        self.dateEdit_nascita_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_nascita_Clienti.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_nascita_Clienti.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit_nascita_Clienti.setCalendarPopup(True)
        self.dateEdit_nascita_Clienti.setObjectName("dateEdit_nascita_Clienti")
        self.gridLayout.addWidget(self.dateEdit_nascita_Clienti, 1, 3, 1, 1)
        self.lineEdit_nome_Cliente = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        self.lineEdit_nome_Cliente.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nome_Cliente.setFont(font)
        self.lineEdit_nome_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nome_Cliente.setObjectName("lineEdit_nome_Cliente")
        self.gridLayout.addWidget(self.lineEdit_nome_Cliente, 0, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_CodFis_Cliente = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_CodFis_Cliente.setFont(font)
        self.lineEdit_CodFis_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CodFis_Cliente.setObjectName("lineEdit_CodFis_Cliente")
        self.horizontalLayout.addWidget(self.lineEdit_CodFis_Cliente)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.lineEdit_Cognome_Cliente = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Cognome_Cliente.setFont(font)
        self.lineEdit_Cognome_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Cognome_Cliente.setObjectName("lineEdit_Cognome_Cliente")
        self.gridLayout.addWidget(self.lineEdit_Cognome_Cliente, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_Nazione_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Nazione_Clienti.setFont(font)
        self.lineEdit_Nazione_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Nazione_Clienti.setObjectName("lineEdit_Nazione_Clienti")
        self.gridLayout.addWidget(self.lineEdit_Nazione_Clienti, 3, 6, 1, 1)
        self.lineEdit_Email_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Email_Clienti.setFont(font)
        self.lineEdit_Email_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Email_Clienti.setObjectName("lineEdit_Email_Clienti")
        self.gridLayout.addWidget(self.lineEdit_Email_Clienti, 7, 1, 1, 1)
        self.comboBox_Residenza_Cliente = QtWidgets.QComboBox(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_Residenza_Cliente.setFont(font)
        self.comboBox_Residenza_Cliente.setEditable(True)
        self.comboBox_Residenza_Cliente.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_Residenza_Cliente.setObjectName("comboBox_Residenza_Cliente")
        self.comboBox_Residenza_Cliente.addItem("")
        self.comboBox_Residenza_Cliente.addItem("")
        self.comboBox_Residenza_Cliente.addItem("")
        self.comboBox_Residenza_Cliente.addItem("")
        self.comboBox_Residenza_Cliente.addItem("")
        self.gridLayout.addWidget(self.comboBox_Residenza_Cliente, 1, 6, 1, 1)
        self.comboBox_sesso_cliente = QtWidgets.QComboBox(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_sesso_cliente.setFont(font)
        self.comboBox_sesso_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_sesso_cliente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_sesso_cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_sesso_cliente.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox_sesso_cliente.setEditable(False)
        self.comboBox_sesso_cliente.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_sesso_cliente.setDuplicatesEnabled(False)
        self.comboBox_sesso_cliente.setFrame(True)
        self.comboBox_sesso_cliente.setObjectName("comboBox_sesso_cliente")
        self.comboBox_sesso_cliente.addItem("")
        self.comboBox_sesso_cliente.addItem("")
        self.comboBox_sesso_cliente.addItem("")
        self.gridLayout.addWidget(self.comboBox_sesso_cliente, 0, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.lineEdit_Prov_Cliente = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Prov_Cliente.setFont(font)
        self.lineEdit_Prov_Cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Prov_Cliente.setObjectName("lineEdit_Prov_Cliente")
        self.gridLayout.addWidget(self.lineEdit_Prov_Cliente, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 2, 1, 1)
        self.lineEdit_CAP_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_CAP_Clienti.setFont(font)
        self.lineEdit_CAP_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CAP_Clienti.setObjectName("lineEdit_CAP_Clienti")
        self.gridLayout.addWidget(self.lineEdit_CAP_Clienti, 2, 6, 1, 1)
        self.comboBox_nascita_Cliente = QtWidgets.QComboBox(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_nascita_Cliente.setFont(font)
        self.comboBox_nascita_Cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_nascita_Cliente.setEditable(True)
        self.comboBox_nascita_Cliente.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_nascita_Cliente.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_nascita_Cliente.setProperty("placeholderText", "")
        self.comboBox_nascita_Cliente.setObjectName("comboBox_nascita_Cliente")
        self.comboBox_nascita_Cliente.addItem("")
        self.comboBox_nascita_Cliente.addItem("")
        self.comboBox_nascita_Cliente.addItem("")
        self.comboBox_nascita_Cliente.addItem("")
        self.gridLayout.addWidget(self.comboBox_nascita_Cliente, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self._RilascioDoc_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self._RilascioDoc_Clienti.setFont(font)
        self._RilascioDoc_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self._RilascioDoc_Clienti.setPlaceholderText("")
        self._RilascioDoc_Clienti.setObjectName("_RilascioDoc_Clienti")
        self.gridLayout.addWidget(self._RilascioDoc_Clienti, 6, 1, 1, 1)
        self.lineEdit_Via_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Via_Clienti.setFont(font)
        self.lineEdit_Via_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Via_Clienti.setObjectName("lineEdit_Via_Clienti")
        self.gridLayout.addWidget(self.lineEdit_Via_Clienti, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 2, 1, 1)
        self.lineEdit_Tel_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Tel_Clienti.setFont(font)
        self.lineEdit_Tel_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Tel_Clienti.setObjectName("lineEdit_Tel_Clienti")
        self.gridLayout.addWidget(self.lineEdit_Tel_Clienti, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 7, 4, 1, 1)
        self.comboBox_ModPag_Clienti = QtWidgets.QComboBox(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_ModPag_Clienti.setFont(font)
        self.comboBox_ModPag_Clienti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_ModPag_Clienti.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_ModPag_Clienti.setObjectName("comboBox_ModPag_Clienti")
        self.comboBox_ModPag_Clienti.addItem("")
        self.comboBox_ModPag_Clienti.addItem("")
        self.comboBox_ModPag_Clienti.addItem("")
        self.gridLayout.addWidget(self.comboBox_ModPag_Clienti, 7, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(19, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.comboBox_Doc_Cliente = QtWidgets.QComboBox(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_Doc_Cliente.setFont(font)
        self.comboBox_Doc_Cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_Doc_Cliente.setObjectName("comboBox_Doc_Cliente")
        self.comboBox_Doc_Cliente.addItem("")
        self.comboBox_Doc_Cliente.addItem("")
        self.comboBox_Doc_Cliente.addItem("")
        self.gridLayout.addWidget(self.comboBox_Doc_Cliente, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 2, 1, 1)
        self.dateEdit_Doc_Clienti_Rilascio = QtWidgets.QDateEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_Doc_Clienti_Rilascio.setFont(font)
        self.dateEdit_Doc_Clienti_Rilascio.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_Doc_Clienti_Rilascio.setCalendarPopup(True)
        self.dateEdit_Doc_Clienti_Rilascio.setObjectName("dateEdit_Doc_Clienti_Rilascio")
        self.gridLayout.addWidget(self.dateEdit_Doc_Clienti_Rilascio, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 4, 1, 1)
        self.dateEdit_Doc_Clienti_Scadenza = QtWidgets.QDateEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_Doc_Clienti_Scadenza.setFont(font)
        self.dateEdit_Doc_Clienti_Scadenza.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_Doc_Clienti_Scadenza.setCalendarPopup(True)
        self.dateEdit_Doc_Clienti_Scadenza.setObjectName("dateEdit_Doc_Clienti_Scadenza")
        self.gridLayout.addWidget(self.dateEdit_Doc_Clienti_Scadenza, 5, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 4, 1, 1)
        self.lineEdit_num_Doc = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_num_Doc.setFont(font)
        self.lineEdit_num_Doc.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num_Doc.setObjectName("lineEdit_num_Doc")
        self.gridLayout.addWidget(self.lineEdit_num_Doc, 6, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.lineEdit_Cellulare_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Cellulare_Clienti.setFont(font)
        self.lineEdit_Cellulare_Clienti.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Cellulare_Clienti.setObjectName("lineEdit_Cellulare_Clienti")
        self.gridLayout.addWidget(self.lineEdit_Cellulare_Clienti, 6, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_Anag_Clienti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 3, 0, 1, 1)
        self._InfoCheckIn_Clienti = QtWidgets.QLineEdit(self.tab_Anag_Clienti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._InfoCheckIn_Clienti.sizePolicy().hasHeightForWidth())
        self._InfoCheckIn_Clienti.setSizePolicy(sizePolicy)
        self._InfoCheckIn_Clienti.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self._InfoCheckIn_Clienti.setFont(font)
        self._InfoCheckIn_Clienti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self._InfoCheckIn_Clienti.setObjectName("_InfoCheckIn_Clienti")
        self.gridLayout_7.addWidget(self._InfoCheckIn_Clienti, 4, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.tab_Anag_Clienti, "")
        self.tab_Anag_Fornitori = QtWidgets.QWidget()
        self.tab_Anag_Fornitori.setObjectName("tab_Anag_Fornitori")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Anag_Fornitori)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PB_add_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_add_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_add_Fornitore.setFont(font)
        self.PB_add_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_add_Fornitore.setObjectName("PB_add_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_add_Fornitore)
        self.PB_modifica_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_modifica_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_modifica_Fornitore.setFont(font)
        self.PB_modifica_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_modifica_Fornitore.setObjectName("PB_modifica_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_modifica_Fornitore)
        self.PB_Elimina_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_Elimina_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_Elimina_Fornitore.setFont(font)
        self.PB_Elimina_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_Elimina_Fornitore.setObjectName("PB_Elimina_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_Elimina_Fornitore)
        self.PB_ricerca_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_ricerca_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_ricerca_Fornitore.setFont(font)
        self.PB_ricerca_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_ricerca_Fornitore.setObjectName("PB_ricerca_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_ricerca_Fornitore)
        self.PB_salva_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_salva_Fornitore.setEnabled(True)
        self.PB_salva_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_salva_Fornitore.setFont(font)
        self.PB_salva_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_salva_Fornitore.setObjectName("PB_salva_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_salva_Fornitore)
        self.PB_AnnullaMod_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_AnnullaMod_Fornitore.setEnabled(True)
        self.PB_AnnullaMod_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_AnnullaMod_Fornitore.setFont(font)
        self.PB_AnnullaMod_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_AnnullaMod_Fornitore.setDefault(False)
        self.PB_AnnullaMod_Fornitore.setFlat(False)
        self.PB_AnnullaMod_Fornitore.setObjectName("PB_AnnullaMod_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_AnnullaMod_Fornitore)
        self.PB_CreaPDF_Fornitore = QtWidgets.QPushButton(self.tab_Anag_Fornitori)
        self.PB_CreaPDF_Fornitore.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PB_CreaPDF_Fornitore.setFont(font)
        self.PB_CreaPDF_Fornitore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_CreaPDF_Fornitore.setObjectName("PB_CreaPDF_Fornitore")
        self.horizontalLayout_3.addWidget(self.PB_CreaPDF_Fornitore)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tableWidget_Fornitori = QtWidgets.QTableWidget(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_Fornitori.setFont(font)
        self.tableWidget_Fornitori.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Fornitori.setAlternatingRowColors(True)
        self.tableWidget_Fornitori.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Fornitori.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Fornitori.setObjectName("tableWidget_Fornitori")
        self.tableWidget_Fornitori.setColumnCount(12)
        self.tableWidget_Fornitori.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Fornitori.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Fornitori.setItem(0, 11, item)
        self.tableWidget_Fornitori.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget_Fornitori.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget_Fornitori, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, 20, 10, 20)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_Riferimento = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_Riferimento.setObjectName("lineEdit_Riferimento")
        self.gridLayout_3.addWidget(self.lineEdit_Riferimento, 2, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 3, 0, 1, 1)
        self.lineEdit_Email = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.gridLayout_3.addWidget(self.lineEdit_Email, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 4, 1, 1)
        self.lineEdit_PartitaIVA = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_PartitaIVA.setObjectName("lineEdit_PartitaIVA")
        self.gridLayout_3.addWidget(self.lineEdit_PartitaIVA, 1, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 1, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineEdit_TelefonoRif = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_TelefonoRif.setObjectName("lineEdit_TelefonoRif")
        self.gridLayout_3.addWidget(self.lineEdit_TelefonoRif, 2, 1, 1, 1)
        self.lineEdit_TipoFornitura2 = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_TipoFornitura2.setObjectName("lineEdit_TipoFornitura2")
        self.gridLayout_3.addWidget(self.lineEdit_TipoFornitura2, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.lineEdit_TempoPagamento = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_TempoPagamento.setObjectName("lineEdit_TempoPagamento")
        self.gridLayout_3.addWidget(self.lineEdit_TempoPagamento, 1, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 2, 2, 1, 1)
        self.lineEdit_Telefono = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_Telefono.setObjectName("lineEdit_Telefono")
        self.gridLayout_3.addWidget(self.lineEdit_Telefono, 2, 5, 1, 1)
        self.lineEdit_Fax = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_Fax.setObjectName("lineEdit_Fax")
        self.gridLayout_3.addWidget(self.lineEdit_Fax, 3, 5, 1, 1)
        self.comboBox_ModPag_Fornitori = QtWidgets.QComboBox(self.tab_Anag_Fornitori)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_ModPag_Fornitori.setFont(font)
        self.comboBox_ModPag_Fornitori.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_ModPag_Fornitori.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_ModPag_Fornitori.setObjectName("comboBox_ModPag_Fornitori")
        self.comboBox_ModPag_Fornitori.addItem("")
        self.comboBox_ModPag_Fornitori.addItem("")
        self.comboBox_ModPag_Fornitori.addItem("")
        self.comboBox_ModPag_Fornitori.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_ModPag_Fornitori, 0, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEdit_nomeFornitore = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_nomeFornitore.setText("")
        self.lineEdit_nomeFornitore.setObjectName("lineEdit_nomeFornitore")
        self.gridLayout_3.addWidget(self.lineEdit_nomeFornitore, 0, 1, 1, 1)
        self.lineEdit_TipoFornitura = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_TipoFornitura.setObjectName("lineEdit_TipoFornitura")
        self.gridLayout_3.addWidget(self.lineEdit_TipoFornitura, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_Anag_Fornitori)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 2, 1, 1)
        self.lineEdit_Indirizzo = QtWidgets.QLineEdit(self.tab_Anag_Fornitori)
        self.lineEdit_Indirizzo.setObjectName("lineEdit_Indirizzo")
        self.gridLayout_3.addWidget(self.lineEdit_Indirizzo, 3, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.tab_Anag_Fornitori, "")
        self.tab_Anag_Utenti = QtWidgets.QWidget()
        self.tab_Anag_Utenti.setObjectName("tab_Anag_Utenti")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Anag_Utenti)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pB_Aggiungi_Utenti = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.pB_Aggiungi_Utenti.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pB_Aggiungi_Utenti.setFont(font)
        self.pB_Aggiungi_Utenti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_Aggiungi_Utenti.setObjectName("pB_Aggiungi_Utenti")
        self.horizontalLayout_7.addWidget(self.pB_Aggiungi_Utenti)
        self.pB_Modifica_Utenti = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.pB_Modifica_Utenti.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pB_Modifica_Utenti.setFont(font)
        self.pB_Modifica_Utenti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_Modifica_Utenti.setObjectName("pB_Modifica_Utenti")
        self.horizontalLayout_7.addWidget(self.pB_Modifica_Utenti)
        self.pB_Elimina_Utenti = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.pB_Elimina_Utenti.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pB_Elimina_Utenti.setFont(font)
        self.pB_Elimina_Utenti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_Elimina_Utenti.setObjectName("pB_Elimina_Utenti")
        self.horizontalLayout_7.addWidget(self.pB_Elimina_Utenti)
        self.pB_Salva_Utenti = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.pB_Salva_Utenti.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pB_Salva_Utenti.setFont(font)
        self.pB_Salva_Utenti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_Salva_Utenti.setObjectName("pB_Salva_Utenti")
        self.horizontalLayout_7.addWidget(self.pB_Salva_Utenti)
        self.pB_Annulla_Utenti = QtWidgets.QPushButton(self.tab_Anag_Utenti)
        self.pB_Annulla_Utenti.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pB_Annulla_Utenti.setFont(font)
        self.pB_Annulla_Utenti.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_Annulla_Utenti.setObjectName("pB_Annulla_Utenti")
        self.horizontalLayout_7.addWidget(self.pB_Annulla_Utenti)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.tableWidget_Utenti = QtWidgets.QTableWidget(self.tab_Anag_Utenti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Utenti.sizePolicy().hasHeightForWidth())
        self.tableWidget_Utenti.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_Utenti.setFont(font)
        self.tableWidget_Utenti.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_Utenti.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tableWidget_Utenti.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_Utenti.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_Utenti.setLineWidth(1)
        self.tableWidget_Utenti.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_Utenti.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_Utenti.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_Utenti.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Utenti.setDragEnabled(False)
        self.tableWidget_Utenti.setAlternatingRowColors(True)
        self.tableWidget_Utenti.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Utenti.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Utenti.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_Utenti.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_Utenti.setShowGrid(True)
        self.tableWidget_Utenti.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_Utenti.setObjectName("tableWidget_Utenti")
        self.tableWidget_Utenti.setColumnCount(10)
        self.tableWidget_Utenti.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Utenti.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_Utenti.setItem(0, 9, item)
        self.tableWidget_Utenti.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_Utenti.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_Utenti.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Utenti.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_Utenti.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Utenti.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.tableWidget_Utenti, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_5.setHorizontalSpacing(20)
        self.gridLayout_5.setVerticalSpacing(25)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_43 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.lE_username = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_username.setFont(font)
        self.lE_username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lE_username.setObjectName("lE_username")
        self.gridLayout_5.addWidget(self.lE_username, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 1, 2, 1, 1)
        self.lE_nomeUtente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_nomeUtente.setFont(font)
        self.lE_nomeUtente.setObjectName("lE_nomeUtente")
        self.gridLayout_5.addWidget(self.lE_nomeUtente, 0, 3, 1, 1)
        self.lE_password = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_password.setFont(font)
        self.lE_password.setObjectName("lE_password")
        self.gridLayout_5.addWidget(self.lE_password, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 2, 1, 1)
        self.lE_cognomeUtente = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_cognomeUtente.setFont(font)
        self.lE_cognomeUtente.setObjectName("lE_cognomeUtente")
        self.gridLayout_5.addWidget(self.lE_cognomeUtente, 1, 3, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_5.addWidget(self.label_92, 1, 4, 1, 1)
        self.cB_permessi = QtWidgets.QComboBox(self.tab_Anag_Utenti)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cB_permessi.sizePolicy().hasHeightForWidth())
        self.cB_permessi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cB_permessi.setFont(font)
        self.cB_permessi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_permessi.setMaxVisibleItems(10)
        self.cB_permessi.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cB_permessi.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cB_permessi.setObjectName("cB_permessi")
        self.cB_permessi.addItem("")
        self.cB_permessi.addItem("")
        self.cB_permessi.addItem("")
        self.gridLayout_5.addWidget(self.cB_permessi, 1, 5, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_5.addWidget(self.label_91, 0, 4, 1, 1)
        self.lE_ambito = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_ambito.setFont(font)
        self.lE_ambito.setObjectName("lE_ambito")
        self.gridLayout_5.addWidget(self.lE_ambito, 0, 5, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 2, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_Anag_Utenti)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 2, 4, 1, 1)
        self.lE_Email = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_Email.setFont(font)
        self.lE_Email.setObjectName("lE_Email")
        self.gridLayout_5.addWidget(self.lE_Email, 2, 1, 1, 1)
        self.lE_Cellulare = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_Cellulare.setFont(font)
        self.lE_Cellulare.setObjectName("lE_Cellulare")
        self.gridLayout_5.addWidget(self.lE_Cellulare, 2, 3, 1, 1)
        self.lE_DataNascita = QtWidgets.QLineEdit(self.tab_Anag_Utenti)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lE_DataNascita.setFont(font)
        self.lE_DataNascita.setObjectName("lE_DataNascita")
        self.gridLayout_5.addWidget(self.lE_DataNascita, 2, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.tabWidget_Anagrafiche.addTab(self.tab_Anag_Utenti, "")
        self.gridLayout_6.addWidget(self.tabWidget_Anagrafiche, 0, 0, 1, 1)
        Anagrafiche_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Anagrafiche_Window)
        self.tabWidget_Anagrafiche.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Anagrafiche_Window)

    def retranslateUi(self, Anagrafiche_Window):
        _translate = QtCore.QCoreApplication.translate
        Anagrafiche_Window.setWindowTitle(_translate("Anagrafiche_Window", "Anagrafiche"))
        self.PB_add_Cliente.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.PB_modifica_Cliente.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.PB_Elimina.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.PB_ricerca_Cliente.setText(_translate("Anagrafiche_Window", "Ricerca"))
        self.PB_salva_Cliente.setText(_translate("Anagrafiche_Window", "Salva"))
        self.PB_AnnullaMod_Cliente.setText(_translate("Anagrafiche_Window", "Annulla"))
        self.PB_CreaPDF_Cliente.setText(_translate("Anagrafiche_Window", "CreaPDF"))
        item = self.tableWidget_Anagrafiche.verticalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Cliente_00"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Cognome"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Nome"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Sesso"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "DatadiNascita"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "LuogodiNascita"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "LuogoResidenza"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "ProvResidenza"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "ViaResidenza"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "CapResidenza"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(10)
        item.setText(_translate("Anagrafiche_Window", "CodiceFiscale"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(11)
        item.setText(_translate("Anagrafiche_Window", "Azienda"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(12)
        item.setText(_translate("Anagrafiche_Window", "Nazione"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(13)
        item.setText(_translate("Anagrafiche_Window", "Telefono"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(14)
        item.setText(_translate("Anagrafiche_Window", "Cellulare"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(15)
        item.setText(_translate("Anagrafiche_Window", "Email"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(16)
        item.setText(_translate("Anagrafiche_Window", "TipoDocumento"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(17)
        item.setText(_translate("Anagrafiche_Window", "NumeroDocumento"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(18)
        item.setText(_translate("Anagrafiche_Window", "RilasciatoDa"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(19)
        item.setText(_translate("Anagrafiche_Window", "RilasciatoIl"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(20)
        item.setText(_translate("Anagrafiche_Window", "ModPagamento"))
        item = self.tableWidget_Anagrafiche.horizontalHeaderItem(21)
        item.setText(_translate("Anagrafiche_Window", "InfoCheckIn"))
        __sortingEnabled = self.tableWidget_Anagrafiche.isSortingEnabled()
        self.tableWidget_Anagrafiche.setSortingEnabled(False)
        item = self.tableWidget_Anagrafiche.item(0, 0)
        item.setText(_translate("Anagrafiche_Window", "0000000001"))
        item = self.tableWidget_Anagrafiche.item(0, 1)
        item.setText(_translate("Anagrafiche_Window", "Pretini"))
        item = self.tableWidget_Anagrafiche.item(0, 2)
        item.setText(_translate("Anagrafiche_Window", "Federico"))
        item = self.tableWidget_Anagrafiche.item(0, 3)
        item.setText(_translate("Anagrafiche_Window", "M"))
        item = self.tableWidget_Anagrafiche.item(0, 4)
        item.setText(_translate("Anagrafiche_Window", "06/07/2000"))
        item = self.tableWidget_Anagrafiche.item(0, 5)
        item.setText(_translate("Anagrafiche_Window", "Jesi"))
        item = self.tableWidget_Anagrafiche.item(0, 6)
        item.setText(_translate("Anagrafiche_Window", "Serra dè Conti"))
        item = self.tableWidget_Anagrafiche.item(0, 7)
        item.setText(_translate("Anagrafiche_Window", "AN"))
        item = self.tableWidget_Anagrafiche.item(0, 8)
        item.setText(_translate("Anagrafiche_Window", "Via Trionfi Honorati"))
        item = self.tableWidget_Anagrafiche.item(0, 9)
        item.setText(_translate("Anagrafiche_Window", "60030"))
        item = self.tableWidget_Anagrafiche.item(0, 10)
        item.setText(_translate("Anagrafiche_Window", "CCC"))
        item = self.tableWidget_Anagrafiche.item(0, 11)
        item.setText(_translate("Anagrafiche_Window", "UNIVPM"))
        item = self.tableWidget_Anagrafiche.item(0, 12)
        item.setText(_translate("Anagrafiche_Window", "IT"))
        item = self.tableWidget_Anagrafiche.item(0, 13)
        item.setText(_translate("Anagrafiche_Window", "CCC"))
        item = self.tableWidget_Anagrafiche.item(0, 14)
        item.setText(_translate("Anagrafiche_Window", "CCC"))
        item = self.tableWidget_Anagrafiche.item(0, 15)
        item.setText(_translate("Anagrafiche_Window", "Pretini"))
        item = self.tableWidget_Anagrafiche.item(0, 16)
        item.setText(_translate("Anagrafiche_Window", "Carta d\'Identità"))
        item = self.tableWidget_Anagrafiche.item(0, 17)
        item.setText(_translate("Anagrafiche_Window", "ccc"))
        item = self.tableWidget_Anagrafiche.item(0, 18)
        item.setText(_translate("Anagrafiche_Window", "ccc"))
        item = self.tableWidget_Anagrafiche.item(0, 19)
        item.setText(_translate("Anagrafiche_Window", "22/12/2018"))
        item = self.tableWidget_Anagrafiche.item(0, 20)
        item.setText(_translate("Anagrafiche_Window", "Carta"))
        item = self.tableWidget_Anagrafiche.item(0, 21)
        item.setText(_translate("Anagrafiche_Window", "Il cliente ha richiesto di un aiuto per il trasporto dei bagagli in camera"))
        self.tableWidget_Anagrafiche.setSortingEnabled(__sortingEnabled)
        self.dateEdit_nascita_Clienti.setDisplayFormat(_translate("Anagrafiche_Window", "dd/MM/yyyy"))
        self.label.setText(_translate("Anagrafiche_Window", "Codice Fiscale"))
        self.label_21.setText(_translate("Anagrafiche_Window", "Nazione"))
        self.label_2.setText(_translate("Anagrafiche_Window", "Cognome"))
        self.comboBox_Residenza_Cliente.setItemText(0, _translate("Anagrafiche_Window", "Serra de\' Conti"))
        self.comboBox_Residenza_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Fermo"))
        self.comboBox_Residenza_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Jesi"))
        self.comboBox_Residenza_Cliente.setItemText(3, _translate("Anagrafiche_Window", "Senigalli"))
        self.comboBox_Residenza_Cliente.setItemText(4, _translate("Anagrafiche_Window", "Ancona"))
        self.comboBox_sesso_cliente.setProperty("placeholderText", _translate("Anagrafiche_Window", "Genere"))
        self.comboBox_sesso_cliente.setItemText(0, _translate("Anagrafiche_Window", "Maschio"))
        self.comboBox_sesso_cliente.setItemText(1, _translate("Anagrafiche_Window", "Femmina"))
        self.comboBox_sesso_cliente.setItemText(2, _translate("Anagrafiche_Window", "Altro"))
        self.label_7.setText(_translate("Anagrafiche_Window", "Residente a"))
        self.label_9.setText(_translate("Anagrafiche_Window", "Prov"))
        self.label_4.setText(_translate("Anagrafiche_Window", "Sesso"))
        self.label_6.setText(_translate("Anagrafiche_Window", "il"))
        self.label_3.setText(_translate("Anagrafiche_Window", "Nome"))
        self.label_20.setText(_translate("Anagrafiche_Window", "Via"))
        self.comboBox_nascita_Cliente.setItemText(0, _translate("Anagrafiche_Window", "Serra dè Conti"))
        self.comboBox_nascita_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Jesi"))
        self.comboBox_nascita_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Senigallia"))
        self.comboBox_nascita_Cliente.setItemText(3, _translate("Anagrafiche_Window", "Ancona"))
        self.label_5.setText(_translate("Anagrafiche_Window", "Nato a"))
        self.label_10.setText(_translate("Anagrafiche_Window", "E-Mail"))
        self.label_8.setText(_translate("Anagrafiche_Window", "CAP"))
        self.label_16.setText(_translate("Anagrafiche_Window", "Rilasciato \n"
"da "))
        self.label_18.setText(_translate("Anagrafiche_Window", "Telefono"))
        self.label_22.setText(_translate("Anagrafiche_Window", "Modalità di \n"
"Pagamento"))
        self.comboBox_ModPag_Clienti.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli una modalità"))
        self.comboBox_ModPag_Clienti.setItemText(0, _translate("Anagrafiche_Window", "Assegno"))
        self.comboBox_ModPag_Clienti.setItemText(1, _translate("Anagrafiche_Window", "Carta"))
        self.comboBox_ModPag_Clienti.setItemText(2, _translate("Anagrafiche_Window", "Contanti"))
        self.label_11.setText(_translate("Anagrafiche_Window", "Tipo \n"
"Documeto"))
        self.comboBox_Doc_Cliente.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli Documento"))
        self.comboBox_Doc_Cliente.setItemText(0, _translate("Anagrafiche_Window", "Carta d\'Identità"))
        self.comboBox_Doc_Cliente.setItemText(1, _translate("Anagrafiche_Window", "Patente"))
        self.comboBox_Doc_Cliente.setItemText(2, _translate("Anagrafiche_Window", "Passaporto"))
        self.label_13.setText(_translate("Anagrafiche_Window", "Rilasciato \n"
"il"))
        self.label_15.setText(_translate("Anagrafiche_Window", "Scandenza"))
        self.label_12.setText(_translate("Anagrafiche_Window", "n°"))
        self.label_17.setText(_translate("Anagrafiche_Window", "Cellulare"))
        self.label_14.setText(_translate("Anagrafiche_Window", "Info \n"
"CheckIn"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.tab_Anag_Clienti), _translate("Anagrafiche_Window", "Clienti"))
        self.PB_add_Fornitore.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.PB_modifica_Fornitore.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.PB_Elimina_Fornitore.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.PB_ricerca_Fornitore.setText(_translate("Anagrafiche_Window", "Ricerca"))
        self.PB_salva_Fornitore.setText(_translate("Anagrafiche_Window", "Salva"))
        self.PB_AnnullaMod_Fornitore.setText(_translate("Anagrafiche_Window", "Annulla"))
        self.PB_CreaPDF_Fornitore.setText(_translate("Anagrafiche_Window", "CreaPDF"))
        item = self.tableWidget_Fornitori.verticalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Fornitore 1."))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Nome Fornitore"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Tipo Fornitura"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Tipo Fortnitura 2"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "Telefono rif."))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "E-Mail"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "Indirizzo"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "Partita IVA"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "Riferimento"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "Modalità di Pagamento"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(10)
        item.setText(_translate("Anagrafiche_Window", "Telefono"))
        item = self.tableWidget_Fornitori.horizontalHeaderItem(11)
        item.setText(_translate("Anagrafiche_Window", "Fax"))
        __sortingEnabled = self.tableWidget_Fornitori.isSortingEnabled()
        self.tableWidget_Fornitori.setSortingEnabled(False)
        item = self.tableWidget_Fornitori.item(0, 0)
        item.setText(_translate("Anagrafiche_Window", "000001"))
        item = self.tableWidget_Fornitori.item(0, 1)
        item.setText(_translate("Anagrafiche_Window", "Acqua_SPA"))
        item = self.tableWidget_Fornitori.item(0, 2)
        item.setText(_translate("Anagrafiche_Window", "Acqua"))
        item = self.tableWidget_Fornitori.item(0, 3)
        item.setText(_translate("Anagrafiche_Window", "-"))
        item = self.tableWidget_Fornitori.item(0, 4)
        item.setText(_translate("Anagrafiche_Window", "0734567821"))
        item = self.tableWidget_Fornitori.item(0, 5)
        item.setText(_translate("Anagrafiche_Window", "acqua@gmail.com"))
        item = self.tableWidget_Fornitori.item(0, 6)
        item.setText(_translate("Anagrafiche_Window", "Via dell\'Acqua"))
        item = self.tableWidget_Fornitori.item(0, 7)
        item.setText(_translate("Anagrafiche_Window", "3-2 per l\'acqua"))
        item = self.tableWidget_Fornitori.item(0, 8)
        item.setText(_translate("Anagrafiche_Window", "boh"))
        item = self.tableWidget_Fornitori.item(0, 9)
        item.setText(_translate("Anagrafiche_Window", "contanti"))
        item = self.tableWidget_Fornitori.item(0, 10)
        item.setText(_translate("Anagrafiche_Window", "0390929212"))
        item = self.tableWidget_Fornitori.item(0, 11)
        item.setText(_translate("Anagrafiche_Window", "143135134135"))
        self.tableWidget_Fornitori.setSortingEnabled(__sortingEnabled)
        self.label_31.setText(_translate("Anagrafiche_Window", "E-Mail:"))
        self.label_29.setText(_translate("Anagrafiche_Window", "Fax:"))
        self.label_32.setText(_translate("Anagrafiche_Window", "Tempo pagamento:"))
        self.label_25.setText(_translate("Anagrafiche_Window", "Telefono rif. :"))
        self.label_30.setText(_translate("Anagrafiche_Window", "Tipo fornitura 2:"))
        self.label_24.setText(_translate("Anagrafiche_Window", "Partita IVA:"))
        self.label_28.setText(_translate("Anagrafiche_Window", "Telefono:"))
        self.label_23.setText(_translate("Anagrafiche_Window", "Modalità pagamento:"))
        self.label_19.setText(_translate("Anagrafiche_Window", "Riferimento:"))
        self.comboBox_ModPag_Fornitori.setProperty("placeholderText", _translate("Anagrafiche_Window", "Scegli una modalità"))
        self.comboBox_ModPag_Fornitori.setItemText(0, _translate("Anagrafiche_Window", "Assegno"))
        self.comboBox_ModPag_Fornitori.setItemText(1, _translate("Anagrafiche_Window", "Bancomat"))
        self.comboBox_ModPag_Fornitori.setItemText(2, _translate("Anagrafiche_Window", "Carta"))
        self.comboBox_ModPag_Fornitori.setItemText(3, _translate("Anagrafiche_Window", "Contanti"))
        self.label_33.setText(_translate("Anagrafiche_Window", "Nome fornitore:"))
        self.label_26.setText(_translate("Anagrafiche_Window", "Indirizzo:"))
        self.label_27.setText(_translate("Anagrafiche_Window", "Tipo fornitura:"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.tab_Anag_Fornitori), _translate("Anagrafiche_Window", "Fornitori"))
        self.pB_Aggiungi_Utenti.setText(_translate("Anagrafiche_Window", "Aggiungi"))
        self.pB_Modifica_Utenti.setText(_translate("Anagrafiche_Window", "Modifica"))
        self.pB_Elimina_Utenti.setText(_translate("Anagrafiche_Window", "Elimina"))
        self.pB_Salva_Utenti.setText(_translate("Anagrafiche_Window", "Salva"))
        self.pB_Annulla_Utenti.setText(_translate("Anagrafiche_Window", "Annulla"))
        item = self.tableWidget_Utenti.verticalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Utente_00"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(0)
        item.setText(_translate("Anagrafiche_Window", "Id"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(1)
        item.setText(_translate("Anagrafiche_Window", "Cognome"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(2)
        item.setText(_translate("Anagrafiche_Window", "Nome"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(3)
        item.setText(_translate("Anagrafiche_Window", "Username"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(4)
        item.setText(_translate("Anagrafiche_Window", "Password"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(5)
        item.setText(_translate("Anagrafiche_Window", "Permessi"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(6)
        item.setText(_translate("Anagrafiche_Window", "Ambito"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(7)
        item.setText(_translate("Anagrafiche_Window", "E-Mail"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(8)
        item.setText(_translate("Anagrafiche_Window", "Cellulare"))
        item = self.tableWidget_Utenti.horizontalHeaderItem(9)
        item.setText(_translate("Anagrafiche_Window", "Data di Nascita"))
        __sortingEnabled = self.tableWidget_Utenti.isSortingEnabled()
        self.tableWidget_Utenti.setSortingEnabled(False)
        item = self.tableWidget_Utenti.item(0, 0)
        item.setText(_translate("Anagrafiche_Window", "00001"))
        item = self.tableWidget_Utenti.item(0, 1)
        item.setText(_translate("Anagrafiche_Window", "Corona"))
        item = self.tableWidget_Utenti.item(0, 2)
        item.setText(_translate("Anagrafiche_Window", "Fabrizio"))
        item = self.tableWidget_Utenti.item(0, 3)
        item.setText(_translate("Anagrafiche_Window", "admin"))
        item = self.tableWidget_Utenti.item(0, 4)
        item.setText(_translate("Anagrafiche_Window", "admin"))
        item = self.tableWidget_Utenti.item(0, 5)
        item.setText(_translate("Anagrafiche_Window", "Admin"))
        item = self.tableWidget_Utenti.item(0, 6)
        item.setText(_translate("Anagrafiche_Window", "Drogato"))
        item = self.tableWidget_Utenti.item(0, 7)
        item.setText(_translate("Anagrafiche_Window", "f.corona@gmail.com"))
        item = self.tableWidget_Utenti.item(0, 8)
        item.setText(_translate("Anagrafiche_Window", "3334456637"))
        item = self.tableWidget_Utenti.item(0, 9)
        item.setText(_translate("Anagrafiche_Window", "18/04/1967"))
        self.tableWidget_Utenti.setSortingEnabled(__sortingEnabled)
        self.label_43.setText(_translate("Anagrafiche_Window", "Password:"))
        self.label_42.setText(_translate("Anagrafiche_Window", "Username:"))
        self.label_45.setText(_translate("Anagrafiche_Window", "Cognome:"))
        self.label_44.setText(_translate("Anagrafiche_Window", "Nome:"))
        self.label_92.setText(_translate("Anagrafiche_Window", "Permessi:"))
        self.cB_permessi.setCurrentText(_translate("Anagrafiche_Window", "Admin"))
        self.cB_permessi.setItemText(0, _translate("Anagrafiche_Window", "Admin"))
        self.cB_permessi.setItemText(1, _translate("Anagrafiche_Window", "Responsabile"))
        self.cB_permessi.setItemText(2, _translate("Anagrafiche_Window", "Dipendente"))
        self.label_91.setText(_translate("Anagrafiche_Window", "Ambito:"))
        self.label_46.setText(_translate("Anagrafiche_Window", "E-Mail"))
        self.label_47.setText(_translate("Anagrafiche_Window", "Cellulare"))
        self.label_48.setText(_translate("Anagrafiche_Window", "Data di Nascita"))
        self.tabWidget_Anagrafiche.setTabText(self.tabWidget_Anagrafiche.indexOf(self.tab_Anag_Utenti), _translate("Anagrafiche_Window", "Utenti"))
