'''
__author__: Federico Pretini
'''
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QCursor


class Ui_AggiornaMenuView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Aggiorna Menù")
        MainWindow.resize(888, 425)
        MainWindow.setMinimumSize(QtCore.QSize(888, 425))
        MainWindow.setMaximumSize(QtCore.QSize(888, 425))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_aggiungi = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pB_aggiungi.setFont(font)
        self.pB_aggiungi.setObjectName("pB_aggiungi")
        self.pB_aggiungi.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.pB_aggiungi)
        self.pB_elimina = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pB_elimina.setFont(font)
        self.pB_elimina.setObjectName("pB_elimina")
        self.pB_elimina.setEnabled(False)
        self.pB_elimina.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.pB_elimina)
        self.pB_annulla = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pB_annulla.setFont(font)
        self.pB_annulla.setObjectName("pB_annulla")
        self.pB_annulla.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.pB_annulla)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_MenuRistorante = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_MenuRistorante.setMinimumSize(QtCore.QSize(866, 312))
        self.tableWidget_MenuRistorante.setMaximumSize(QtCore.QSize(866, 312))
        self.tableWidget_MenuRistorante.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_MenuRistorante.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_MenuRistorante.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_MenuRistorante.setObjectName("tableWidget_MenuRistorante")
        self.tableWidget_MenuRistorante.setColumnCount(3)
        self.tableWidget_MenuRistorante.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_MenuRistorante.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_MenuRistorante.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_MenuRistorante.setHorizontalHeaderItem(2, item)
        self.tableWidget_MenuRistorante.horizontalHeader().setDefaultSectionSize(288)
        self.tableWidget_MenuRistorante.horizontalHeader().setMinimumSectionSize(60)
        self.verticalLayout.addWidget(self.tableWidget_MenuRistorante)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineE_nome = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineE_nome.sizePolicy().hasHeightForWidth())
        self.lineE_nome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.lineE_nome.setFont(font)
        self.lineE_nome.setText("")
        self.lineE_nome.setObjectName("lineE_nome")
        self.horizontalLayout_2.addWidget(self.lineE_nome)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cB_categoria = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.cB_categoria.setFont(font)
        self.cB_categoria.setEditable(False)
        self.cB_categoria.setObjectName("cB_categoria")
        self.set_combo(self.cB_categoria, font)
        self.cB_categoria.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_2.addWidget(self.cB_categoria)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinB_prezzo = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.spinB_prezzo.setFont(font)
        self.spinB_prezzo.setAlignment(QtCore.Qt.AlignCenter)
        self.spinB_prezzo.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinB_prezzo.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.spinB_prezzo.setObjectName("spinB_prezzo")
        self.horizontalLayout_2.addWidget(self.spinB_prezzo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def set_combo(self, combo, font):
        combo.setEditable(True)
        line_e = combo.lineEdit()
        line_e.setAlignment(QtCore.Qt.AlignCenter)
        line_e.setFont(font)
        line_e.setReadOnly(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aggiorna Listino"))
        self.pB_aggiungi.setText(_translate("MainWindow", "Aggiungi"))
        self.pB_elimina.setText(_translate("MainWindow", "Elimina"))
        self.pB_annulla.setText(_translate("MainWindow", "Annulla"))
        item = self.tableWidget_MenuRistorante.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tableWidget_MenuRistorante.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CATEGORIA"))
        item = self.tableWidget_MenuRistorante.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PREZZO"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_2.setText(_translate("MainWindow", "Categoria:"))
        self.label_3.setText(_translate("MainWindow", "Prezzo (€):"))
