'''
__author__: Alessandro Rongoni
'''
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrenotaRistoranteView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 200)
        MainWindow.setMinimumSize(QtCore.QSize(800,200))
        MainWindow.setMaximumSize(QtCore.QSize(800,200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cB_nominativo = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cB_nominativo.setFont(font)
        self.cB_nominativo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_nominativo.setObjectName("cB_nominativo")
        self.horizontalLayout_4.addWidget(self.cB_nominativo)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sb_persone = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sb_persone.setFont(font)
        self.sb_persone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sb_persone.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_persone.setMinimum(1)
        self.sb_persone.setMaximum(15)
        self.sb_persone.setObjectName("sb_persone")
        self.horizontalLayout_2.addWidget(self.sb_persone)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cB_camera = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cB_camera.setFont(font)
        self.cB_camera.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cB_camera.setObjectName("cB_camera")
        self.cB_camera.setEnabled(False)
        self.horizontalLayout_3.addWidget(self.cB_camera)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_prenota = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pB_prenota.setFont(font)
        self.pB_prenota.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_prenota.setObjectName("pB_prenota")
        self.horizontalLayout.addWidget(self.pB_prenota)
        self.pB_annulla = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pB_annulla.setFont(font)
        self.pB_annulla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pB_annulla.setObjectName("pB_annulla")
        self.horizontalLayout.addWidget(self.pB_annulla)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prenota tavolo"))
        self.label_3.setText(_translate("MainWindow", "Nominativo:"))
        self.label_2.setText(_translate("MainWindow", "Persone:"))
        self.label.setText(_translate("MainWindow", "Camera:"))
        self.pB_prenota.setText(_translate("MainWindow", "Prenota"))
        self.pB_annulla.setText(_translate("MainWindow", "Annulla"))
