from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RistoranteView_1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 257)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.de_data = QtWidgets.QDateEdit(self.tab)
        self.de_data.setObjectName("de_data")
        self.gridLayout_4.addWidget(self.de_data, 0, 1, 1, 1)
        self.cb_orario = QtWidgets.QComboBox(self.tab)
        self.cb_orario.setObjectName("cb_orario")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.gridLayout_4.addWidget(self.cb_orario, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_t2 = QtWidgets.QPushButton(self.tab)
        self.button_t2.setObjectName("button_t2")
        self.gridLayout_2.addWidget(self.button_t2, 1, 1, 1, 1)
        self.button_t4 = QtWidgets.QPushButton(self.tab)
        self.button_t4.setObjectName("button_t4")
        self.gridLayout_2.addWidget(self.button_t4, 1, 3, 1, 1)
        self.button_t16 = QtWidgets.QPushButton(self.tab)
        self.button_t16.setObjectName("button_t16")
        self.gridLayout_2.addWidget(self.button_t16, 4, 3, 1, 1)
        self.button_t5 = QtWidgets.QPushButton(self.tab)
        self.button_t5.setObjectName("button_t5")
        self.gridLayout_2.addWidget(self.button_t5, 2, 0, 1, 1)
        self.button_t7 = QtWidgets.QPushButton(self.tab)
        self.button_t7.setObjectName("button_t7")
        self.gridLayout_2.addWidget(self.button_t7, 2, 2, 1, 1)
        self.button_t1 = QtWidgets.QPushButton(self.tab)
        self.button_t1.setObjectName("button_t1")
        self.gridLayout_2.addWidget(self.button_t1, 1, 0, 1, 1)
        self.button_t12 = QtWidgets.QPushButton(self.tab)
        self.button_t12.setObjectName("button_t12")
        self.gridLayout_2.addWidget(self.button_t12, 3, 3, 1, 1)
        self.button_t15 = QtWidgets.QPushButton(self.tab)
        self.button_t15.setObjectName("button_t15")
        self.gridLayout_2.addWidget(self.button_t15, 4, 2, 1, 1)
        self.button_t8 = QtWidgets.QPushButton(self.tab)
        self.button_t8.setObjectName("button_t8")
        self.gridLayout_2.addWidget(self.button_t8, 2, 3, 1, 1)
        self.button_t11 = QtWidgets.QPushButton(self.tab)
        self.button_t11.setObjectName("button_t11")
        self.gridLayout_2.addWidget(self.button_t11, 3, 2, 1, 1)
        self.button_t6 = QtWidgets.QPushButton(self.tab)
        self.button_t6.setObjectName("button_t6")
        self.gridLayout_2.addWidget(self.button_t6, 2, 1, 1, 1)
        self.button_t10 = QtWidgets.QPushButton(self.tab)
        self.button_t10.setObjectName("button_t10")
        self.gridLayout_2.addWidget(self.button_t10, 3, 1, 1, 1)
        self.button_t3 = QtWidgets.QPushButton(self.tab)
        self.button_t3.setObjectName("button_t3")
        self.gridLayout_2.addWidget(self.button_t3, 1, 2, 1, 1)
        self.button_t9 = QtWidgets.QPushButton(self.tab)
        self.button_t9.setObjectName("button_t9")
        self.gridLayout_2.addWidget(self.button_t9, 3, 0, 1, 1)
        self.button_t14 = QtWidgets.QPushButton(self.tab)
        self.button_t14.setObjectName("button_t14")
        self.gridLayout_2.addWidget(self.button_t14, 4, 1, 1, 1)
        self.button_t13 = QtWidgets.QPushButton(self.tab)
        self.button_t13.setObjectName("button_t13")
        self.gridLayout_2.addWidget(self.button_t13, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.mostra = QtWidgets.QWidget()
        self.mostra.setObjectName("mostra")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mostra)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.mostra)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cb_tavolo = QtWidgets.QComboBox(self.mostra)
        self.cb_tavolo.setObjectName("cb_tavolo")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.horizontalLayout.addWidget(self.cb_tavolo)
        self.line_3 = QtWidgets.QFrame(self.mostra)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.mostra)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.de_data_2 = QtWidgets.QDateEdit(self.mostra)
        self.de_data_2.setObjectName("de_data_2")
        self.horizontalLayout.addWidget(self.de_data_2)
        self.line_4 = QtWidgets.QFrame(self.mostra)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.mostra)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.cb_orario_2 = QtWidgets.QComboBox(self.mostra)
        self.cb_orario_2.setObjectName("cb_orario_2")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.horizontalLayout.addWidget(self.cb_orario_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.mostra)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.tabella_prenotazioni = QtWidgets.QTableWidget(self.mostra)
        self.tabella_prenotazioni.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabella_prenotazioni.setObjectName("tabella_prenotazioni")
        self.tabella_prenotazioni.setColumnCount(6)
        self.tabella_prenotazioni.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_prenotazioni.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tabella_prenotazioni)
        self.tabWidget.addTab(self.mostra, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Orario"))
        self.label.setText(_translate("MainWindow", "Data"))
        self.cb_orario.setItemText(0, _translate("MainWindow", "12:00 - 14:00"))
        self.cb_orario.setItemText(1, _translate("MainWindow", "14:00 - 16:00"))
        self.cb_orario.setItemText(2, _translate("MainWindow", "18:00 - 20:00"))
        self.cb_orario.setItemText(3, _translate("MainWindow", "20:00 - 22:00"))
        self.cb_orario.setItemText(4, _translate("MainWindow", "22:00 - 24:00"))
        self.button_t2.setText(_translate("MainWindow", "Tavolo 2"))
        self.button_t4.setText(_translate("MainWindow", "Tavolo 4"))
        self.button_t16.setText(_translate("MainWindow", "Tavolo 16"))
        self.button_t5.setText(_translate("MainWindow", "Tavolo 5"))
        self.button_t7.setText(_translate("MainWindow", "Tavolo 7"))
        self.button_t1.setText(_translate("MainWindow", "Tavolo 1"))
        self.button_t12.setText(_translate("MainWindow", "Tavolo 12"))
        self.button_t15.setText(_translate("MainWindow", "Tavolo 15"))
        self.button_t8.setText(_translate("MainWindow", "Tavolo 8"))
        self.button_t11.setText(_translate("MainWindow", "Tavolo 11"))
        self.button_t6.setText(_translate("MainWindow", "Tavolo 6"))
        self.button_t10.setText(_translate("MainWindow", "Tavolo 10"))
        self.button_t3.setText(_translate("MainWindow", "Tavolo 3"))
        self.button_t9.setText(_translate("MainWindow", "Tavolo 9"))
        self.button_t14.setText(_translate("MainWindow", "Tavolo 14"))
        self.button_t13.setText(_translate("MainWindow", "Tavolo 13"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tavoli"))
        self.label_5.setText(_translate("MainWindow", "Tavolo"))
        self.cb_tavolo.setItemText(0, _translate("MainWindow", "Tutti"))
        self.cb_tavolo.setItemText(1, _translate("MainWindow", "Tavolo 1"))
        self.cb_tavolo.setItemText(2, _translate("MainWindow", "Tavolo 2"))
        self.cb_tavolo.setItemText(3, _translate("MainWindow", "Tavolo 3"))
        self.cb_tavolo.setItemText(4, _translate("MainWindow", "Tavolo 4"))
        self.cb_tavolo.setItemText(5, _translate("MainWindow", "Tavolo 5"))
        self.cb_tavolo.setItemText(6, _translate("MainWindow", "Tavolo 6"))
        self.cb_tavolo.setItemText(7, _translate("MainWindow", "Tavolo 7"))
        self.cb_tavolo.setItemText(8, _translate("MainWindow", "Tavolo 8"))
        self.cb_tavolo.setItemText(9, _translate("MainWindow", "Tavolo 9"))
        self.cb_tavolo.setItemText(10, _translate("MainWindow", "Tavolo 10"))
        self.cb_tavolo.setItemText(11, _translate("MainWindow", "Tavolo 11"))
        self.cb_tavolo.setItemText(12, _translate("MainWindow", "Tavolo 12"))
        self.cb_tavolo.setItemText(13, _translate("MainWindow", "Tavolo 13"))
        self.cb_tavolo.setItemText(14, _translate("MainWindow", "Tavolo 14"))
        self.cb_tavolo.setItemText(15, _translate("MainWindow", "Tavolo 15"))
        self.cb_tavolo.setItemText(16, _translate("MainWindow", "Tavolo 16"))
        self.label_3.setText(_translate("MainWindow", "Giorno"))
        self.label_4.setText(_translate("MainWindow", "Orario"))
        self.cb_orario_2.setItemText(0, _translate("MainWindow", "Tutti"))
        self.cb_orario_2.setItemText(1, _translate("MainWindow", "12:00 - 14:00"))
        self.cb_orario_2.setItemText(2, _translate("MainWindow", "14:00 - 16:00"))
        self.cb_orario_2.setItemText(3, _translate("MainWindow", "18:00 - 20:00"))
        self.cb_orario_2.setItemText(4, _translate("MainWindow", "20:00 - 22:00"))
        self.cb_orario_2.setItemText(5, _translate("MainWindow", "22:00 - 24:00"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nominativo"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Camera"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Persone"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ora"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tavolo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mostra), _translate("MainWindow", "Prenotazioni"))
