# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ristorante_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RistoranteView(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1722, 953)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\resources/logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background-image: url(ui/resources/ristorante/50-504378_restaurant-hd-wallpaper-restaurant-hd.jpg);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.de_data = QtWidgets.QDateEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.de_data.setFont(font)
        self.de_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.de_data.setStyleSheet("background-image: url(:/ristorante/8-85556_silver-mat-color.jpg);")
        self.de_data.setCalendarPopup(True)
        self.de_data.setObjectName("de_data")
        self.gridLayout_4.addWidget(self.de_data, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));background-image: url(:/ristorante/tpg.png);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.cb_orario = QtWidgets.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.cb_orario.setFont(font)
        self.cb_orario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_orario.setStyleSheet("background-image: url(:/ristorante/8-85556_silver-mat-color.jpg);")
        self.cb_orario.setObjectName("cb_orario")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.cb_orario.addItem("")
        self.gridLayout_4.addWidget(self.cb_orario, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 30, 10, 50)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Tavolo_2 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_2.sizePolicy().hasHeightForWidth())
        self.Tavolo_2.setSizePolicy(sizePolicy)
        self.Tavolo_2.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_2.setFont(font)
        self.Tavolo_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_2.setAutoFillBackground(False)
        self.Tavolo_2.setStyleSheet("#Tavolo_2{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_2:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/resources/ristorante/LogoMakr-2rm3uC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tavolo_2.setIcon(icon1)
        self.Tavolo_2.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_2.setObjectName("Tavolo_2")
        self.gridLayout_2.addWidget(self.Tavolo_2, 1, 1, 1, 1)
        self.Tavolo_16 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_16.sizePolicy().hasHeightForWidth())
        self.Tavolo_16.setSizePolicy(sizePolicy)
        self.Tavolo_16.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_16.setFont(font)
        self.Tavolo_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_16.setAutoFillBackground(False)
        self.Tavolo_16.setStyleSheet("#Tavolo_16{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_16:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_16.setIcon(icon1)
        self.Tavolo_16.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_16.setObjectName("Tavolo_16")
        self.gridLayout_2.addWidget(self.Tavolo_16, 4, 3, 1, 1)
        self.Tavolo_4 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_4.sizePolicy().hasHeightForWidth())
        self.Tavolo_4.setSizePolicy(sizePolicy)
        self.Tavolo_4.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_4.setFont(font)
        self.Tavolo_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_4.setAutoFillBackground(False)
        self.Tavolo_4.setStyleSheet("#Tavolo_4{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_4:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_4.setIcon(icon1)
        self.Tavolo_4.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_4.setObjectName("Tavolo_4")
        self.gridLayout_2.addWidget(self.Tavolo_4, 1, 3, 1, 1)
        self.Tavolo_12 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_12.sizePolicy().hasHeightForWidth())
        self.Tavolo_12.setSizePolicy(sizePolicy)
        self.Tavolo_12.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_12.setFont(font)
        self.Tavolo_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_12.setAutoFillBackground(False)
        self.Tavolo_12.setStyleSheet("#Tavolo_12{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_12:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_12.setIcon(icon1)
        self.Tavolo_12.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_12.setObjectName("Tavolo_12")
        self.gridLayout_2.addWidget(self.Tavolo_12, 3, 3, 1, 1)
        self.Tavolo_5 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_5.sizePolicy().hasHeightForWidth())
        self.Tavolo_5.setSizePolicy(sizePolicy)
        self.Tavolo_5.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_5.setFont(font)
        self.Tavolo_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_5.setAutoFillBackground(False)
        self.Tavolo_5.setStyleSheet("#Tavolo_5{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_5:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_5.setIcon(icon1)
        self.Tavolo_5.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_5.setObjectName("Tavolo_5")
        self.gridLayout_2.addWidget(self.Tavolo_5, 2, 0, 1, 1)
        self.Tavolo_1 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_1.sizePolicy().hasHeightForWidth())
        self.Tavolo_1.setSizePolicy(sizePolicy)
        self.Tavolo_1.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.Tavolo_1.setFont(font)
        self.Tavolo_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_1.setAutoFillBackground(False)
        self.Tavolo_1.setStyleSheet("#Tavolo_1{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_1:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_1.setIcon(icon1)
        self.Tavolo_1.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_1.setAutoDefault(False)
        self.Tavolo_1.setDefault(False)
        self.Tavolo_1.setFlat(False)
        self.Tavolo_1.setObjectName("Tavolo_1")
        self.gridLayout_2.addWidget(self.Tavolo_1, 1, 0, 1, 1)
        self.Tavolo_7 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_7.sizePolicy().hasHeightForWidth())
        self.Tavolo_7.setSizePolicy(sizePolicy)
        self.Tavolo_7.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_7.setFont(font)
        self.Tavolo_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_7.setAutoFillBackground(False)
        self.Tavolo_7.setStyleSheet("#Tavolo_7{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_7:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_7.setIcon(icon1)
        self.Tavolo_7.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_7.setObjectName("Tavolo_7")
        self.gridLayout_2.addWidget(self.Tavolo_7, 2, 2, 1, 1)
        self.Tavolo_6 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_6.sizePolicy().hasHeightForWidth())
        self.Tavolo_6.setSizePolicy(sizePolicy)
        self.Tavolo_6.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_6.setFont(font)
        self.Tavolo_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_6.setAutoFillBackground(False)
        self.Tavolo_6.setStyleSheet("#Tavolo_6{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_6:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_6.setIcon(icon1)
        self.Tavolo_6.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_6.setObjectName("Tavolo_6")
        self.gridLayout_2.addWidget(self.Tavolo_6, 2, 1, 1, 1)
        self.Tavolo_15 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_15.sizePolicy().hasHeightForWidth())
        self.Tavolo_15.setSizePolicy(sizePolicy)
        self.Tavolo_15.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_15.setFont(font)
        self.Tavolo_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_15.setAutoFillBackground(False)
        self.Tavolo_15.setStyleSheet("#Tavolo_15{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_15:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_15.setIcon(icon1)
        self.Tavolo_15.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_15.setObjectName("Tavolo_15")
        self.gridLayout_2.addWidget(self.Tavolo_15, 4, 2, 1, 1)
        self.Tavolo_11 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_11.sizePolicy().hasHeightForWidth())
        self.Tavolo_11.setSizePolicy(sizePolicy)
        self.Tavolo_11.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_11.setFont(font)
        self.Tavolo_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_11.setAutoFillBackground(False)
        self.Tavolo_11.setStyleSheet("#Tavolo_11{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_11:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_11.setIcon(icon1)
        self.Tavolo_11.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_11.setObjectName("Tavolo_11")
        self.gridLayout_2.addWidget(self.Tavolo_11, 3, 2, 1, 1)
        self.Tavolo_8 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_8.sizePolicy().hasHeightForWidth())
        self.Tavolo_8.setSizePolicy(sizePolicy)
        self.Tavolo_8.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_8.setFont(font)
        self.Tavolo_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_8.setAutoFillBackground(False)
        self.Tavolo_8.setStyleSheet("#Tavolo_8{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_8:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_8.setIcon(icon1)
        self.Tavolo_8.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_8.setObjectName("Tavolo_8")
        self.gridLayout_2.addWidget(self.Tavolo_8, 2, 3, 1, 1)
        self.Tavolo_9 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_9.sizePolicy().hasHeightForWidth())
        self.Tavolo_9.setSizePolicy(sizePolicy)
        self.Tavolo_9.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_9.setFont(font)
        self.Tavolo_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_9.setAutoFillBackground(False)
        self.Tavolo_9.setStyleSheet("#Tavolo_9{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_9:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_9.setIcon(icon1)
        self.Tavolo_9.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_9.setObjectName("Tavolo_9")
        self.gridLayout_2.addWidget(self.Tavolo_9, 3, 0, 1, 1)
        self.Tavolo_3 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_3.sizePolicy().hasHeightForWidth())
        self.Tavolo_3.setSizePolicy(sizePolicy)
        self.Tavolo_3.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_3.setFont(font)
        self.Tavolo_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_3.setAutoFillBackground(False)
        self.Tavolo_3.setStyleSheet("#Tavolo_3{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_3:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_3.setIcon(icon1)
        self.Tavolo_3.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_3.setObjectName("Tavolo_3")
        self.gridLayout_2.addWidget(self.Tavolo_3, 1, 2, 1, 1)
        self.Tavolo_10 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_10.sizePolicy().hasHeightForWidth())
        self.Tavolo_10.setSizePolicy(sizePolicy)
        self.Tavolo_10.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_10.setFont(font)
        self.Tavolo_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_10.setAutoFillBackground(False)
        self.Tavolo_10.setStyleSheet("#Tavolo_10{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_10:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_10.setIcon(icon1)
        self.Tavolo_10.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_10.setObjectName("Tavolo_10")
        self.gridLayout_2.addWidget(self.Tavolo_10, 3, 1, 1, 1)
        self.Tavolo_14 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_14.sizePolicy().hasHeightForWidth())
        self.Tavolo_14.setSizePolicy(sizePolicy)
        self.Tavolo_14.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_14.setFont(font)
        self.Tavolo_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_14.setAutoFillBackground(False)
        self.Tavolo_14.setStyleSheet("#Tavolo_14{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_14:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_14.setIcon(icon1)
        self.Tavolo_14.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_14.setObjectName("Tavolo_14")
        self.gridLayout_2.addWidget(self.Tavolo_14, 4, 1, 1, 1)
        self.Tavolo_13 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tavolo_13.sizePolicy().hasHeightForWidth())
        self.Tavolo_13.setSizePolicy(sizePolicy)
        self.Tavolo_13.setMinimumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.Tavolo_13.setFont(font)
        self.Tavolo_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Tavolo_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tavolo_13.setAutoFillBackground(False)
        self.Tavolo_13.setStyleSheet("#Tavolo_13{background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));\n"
"    border-radius:16px;\n"
"    border-style: outset;\n"
"    border: 5px solid black;\n"
"    \n"
"}\n"
"\n"
"#Tavolo_13:pressed{ border-style: inset;\n"
"                                border:4px solid grey;}")
        self.Tavolo_13.setIcon(icon1)
        self.Tavolo_13.setIconSize(QtCore.QSize(110, 120))
        self.Tavolo_13.setObjectName("Tavolo_13")
        self.gridLayout_2.addWidget(self.Tavolo_13, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.mostra = QtWidgets.QWidget()
        self.mostra.setObjectName("mostra")
        self.gridLayout = QtWidgets.QGridLayout(self.mostra)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-image: url(:/ristorante/tpg.png);background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cb_tavolo = QtWidgets.QComboBox(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cb_tavolo.setFont(font)
        self.cb_tavolo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_tavolo.setStyleSheet("background-image: url(:/ristorante/8-85556_silver-mat-color.jpg);")
        self.cb_tavolo.setObjectName("cb_tavolo")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.cb_tavolo.addItem("")
        self.horizontalLayout.addWidget(self.cb_tavolo)
        self.line_3 = QtWidgets.QFrame(self.mostra)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));background-image: url(:/ristorante/tpg.png);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.de_data_2 = QtWidgets.QDateEdit(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.de_data_2.setFont(font)
        self.de_data_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.de_data_2.setStyleSheet("background-image: url(:/ristorante/8-85556_silver-mat-color.jpg);")
        self.de_data_2.setCalendarPopup(True)
        self.de_data_2.setObjectName("de_data_2")
        self.horizontalLayout.addWidget(self.de_data_2)
        self.line_4 = QtWidgets.QFrame(self.mostra)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));background-image: url(:/ristorante/tpg.png);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.cb_orario_2 = QtWidgets.QComboBox(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cb_orario_2.setFont(font)
        self.cb_orario_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cb_orario_2.setStyleSheet("background-image: url(:/ristorante/8-85556_silver-mat-color.jpg);")
        self.cb_orario_2.setObjectName("cb_orario_2")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.cb_orario_2.addItem("")
        self.horizontalLayout.addWidget(self.cb_orario_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.mostra)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabella_prenotazioni = QtWidgets.QTableWidget(self.mostra)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabella_prenotazioni.setFont(font)
        self.tabella_prenotazioni.setStyleSheet("background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 225), stop:1 rgba(255, 255, 255, 227));")
        self.tabella_prenotazioni.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabella_prenotazioni.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabella_prenotazioni.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabella_prenotazioni.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabella_prenotazioni.setObjectName("tabella_prenotazioni")
        self.tabella_prenotazioni.setColumnCount(6)
        self.tabella_prenotazioni.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabella_prenotazioni.setHorizontalHeaderItem(5, item)
        self.tabella_prenotazioni.horizontalHeader().setDefaultSectionSize(280)
        self.tabella_prenotazioni.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tabella_prenotazioni)
        self.pushButton_2 = QtWidgets.QPushButton(self.mostra)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-image: url(:/ristorante/tpg.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 140), stop:1 rgba(255, 255, 255, 165));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget.addTab(self.mostra, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Ristorante"))
        self.label.setText(_translate("mainWindow", "Data:"))
        self.label_2.setText(_translate("mainWindow", "Orario:"))
        self.cb_orario.setItemText(0, _translate("mainWindow", "12:00 - 14:00"))
        self.cb_orario.setItemText(1, _translate("mainWindow", "14:00 - 16:00"))
        self.cb_orario.setItemText(2, _translate("mainWindow", "18:00 - 20:00"))
        self.cb_orario.setItemText(3, _translate("mainWindow", "20:00 - 22:00"))
        self.cb_orario.setItemText(4, _translate("mainWindow", "22:00 - 24:00"))
        self.pushButton.setText(_translate("mainWindow", "Ricerca"))
        self.Tavolo_2.setText(_translate("mainWindow", "2"))
        self.Tavolo_16.setText(_translate("mainWindow", "16"))
        self.Tavolo_4.setText(_translate("mainWindow", "4"))
        self.Tavolo_12.setText(_translate("mainWindow", "12"))
        self.Tavolo_5.setText(_translate("mainWindow", "5"))
        self.Tavolo_1.setText(_translate("mainWindow", "1"))
        self.Tavolo_7.setText(_translate("mainWindow", "7"))
        self.Tavolo_6.setText(_translate("mainWindow", "6"))
        self.Tavolo_15.setText(_translate("mainWindow", "15"))
        self.Tavolo_11.setText(_translate("mainWindow", "11"))
        self.Tavolo_8.setText(_translate("mainWindow", "8"))
        self.Tavolo_9.setText(_translate("mainWindow", "9"))
        self.Tavolo_3.setText(_translate("mainWindow", "3"))
        self.Tavolo_10.setText(_translate("mainWindow", "10"))
        self.Tavolo_14.setText(_translate("mainWindow", "14"))
        self.Tavolo_13.setText(_translate("mainWindow", "13"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Tavoli"))
        self.label_5.setText(_translate("mainWindow", "Tavolo:"))
        self.cb_tavolo.setItemText(0, _translate("mainWindow", "Tutti"))
        self.cb_tavolo.setItemText(1, _translate("mainWindow", "Tavolo 1"))
        self.cb_tavolo.setItemText(2, _translate("mainWindow", "Tavolo 2"))
        self.cb_tavolo.setItemText(3, _translate("mainWindow", "Tavolo 3"))
        self.cb_tavolo.setItemText(4, _translate("mainWindow", "Tavolo 4"))
        self.cb_tavolo.setItemText(5, _translate("mainWindow", "Tavolo 5"))
        self.cb_tavolo.setItemText(6, _translate("mainWindow", "Tavolo 6"))
        self.cb_tavolo.setItemText(7, _translate("mainWindow", "Tavolo 7"))
        self.cb_tavolo.setItemText(8, _translate("mainWindow", "Tavolo 8"))
        self.cb_tavolo.setItemText(9, _translate("mainWindow", "Tavolo 9"))
        self.cb_tavolo.setItemText(10, _translate("mainWindow", "Tavolo 10"))
        self.cb_tavolo.setItemText(11, _translate("mainWindow", "Tavolo 11"))
        self.cb_tavolo.setItemText(12, _translate("mainWindow", "Tavolo 12"))
        self.cb_tavolo.setItemText(13, _translate("mainWindow", "Tavolo 13"))
        self.cb_tavolo.setItemText(14, _translate("mainWindow", "Tavolo 14"))
        self.cb_tavolo.setItemText(15, _translate("mainWindow", "Tavolo 15"))
        self.cb_tavolo.setItemText(16, _translate("mainWindow", "Tavolo 16"))
        self.label_3.setText(_translate("mainWindow", "Giorno:"))
        self.label_4.setText(_translate("mainWindow", "Orario:"))
        self.cb_orario_2.setItemText(0, _translate("mainWindow", "Tutti"))
        self.cb_orario_2.setItemText(1, _translate("mainWindow", "12:00 - 14:00"))
        self.cb_orario_2.setItemText(2, _translate("mainWindow", "14:00 - 16:00"))
        self.cb_orario_2.setItemText(3, _translate("mainWindow", "18:00 - 20:00"))
        self.cb_orario_2.setItemText(4, _translate("mainWindow", "20:00 - 22:00"))
        self.cb_orario_2.setItemText(5, _translate("mainWindow", "22:00 - 24:00"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Tavolo"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Nominativo"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Persone"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Data"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Ora"))
        item = self.tabella_prenotazioni.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Camera"))
        self.pushButton_2.setText(_translate("mainWindow", "Elimina"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mostra), _translate("mainWindow", "Prenotazioni"))
