# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ristorante_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(234, 98)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sb_persone = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_persone.setObjectName("sb_persone")
        self.gridLayout.addWidget(self.sb_persone, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 2)
        self.button_conferma = QtWidgets.QPushButton(self.centralwidget)
        self.button_conferma.setObjectName("button_conferma")
        self.gridLayout.addWidget(self.button_conferma, 2, 0, 1, 1)
        self.button_annulla = QtWidgets.QPushButton(self.centralwidget)
        self.button_annulla.setObjectName("button_annulla")
        self.gridLayout.addWidget(self.button_annulla, 2, 3, 1, 1)
        self.cb_camere = QtWidgets.QComboBox(self.centralwidget)
        self.cb_camere.setObjectName("cb_camere")
        self.gridLayout.addWidget(self.cb_camere, 0, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Camera"))
        self.label_2.setText(_translate("MainWindow", "Persone"))
        self.button_conferma.setText(_translate("MainWindow", "Conferma"))
        self.button_annulla.setText(_translate("MainWindow", "Annulla"))
