# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'permission_allert.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Permission_Allert(object):
    def setupUi(self, Dialog_Permission_Allert):
        Dialog_Permission_Allert.setObjectName("Dialog_Permission_Allert")
        Dialog_Permission_Allert.setWindowModality(QtCore.Qt.NonModal)
        Dialog_Permission_Allert.resize(300, 140)
        Dialog_Permission_Allert.setMinimumSize(QtCore.QSize(300, 140))
        Dialog_Permission_Allert.setMaximumSize(QtCore.QSize(300, 140))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource_logo/logo_small_icon_only_inverted.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Permission_Allert.setWindowIcon(icon)
        Dialog_Permission_Allert.setAccessibleName("")
        Dialog_Permission_Allert.setAccessibleDescription("")
        Dialog_Permission_Allert.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog_Permission_Allert.setSizeGripEnabled(False)
        Dialog_Permission_Allert.setModal(False)
        self.label_2 = QtWidgets.QLabel(Dialog_Permission_Allert)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 210, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog_Permission_Allert)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 220, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog_Permission_Allert)
        self.label.setGeometry(QtCore.QRect(20, 5, 41, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resource_error/Allert_Giallo.png"))
        self.label.setObjectName("label")
        self.pushButton_OK_Error = QtWidgets.QPushButton(Dialog_Permission_Allert)
        self.pushButton_OK_Error.setGeometry(QtCore.QRect(100, 100, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_OK_Error.setFont(font)
        self.pushButton_OK_Error.setObjectName("pushButton_OK_Error")
        self.label_4 = QtWidgets.QLabel(Dialog_Permission_Allert)
        self.label_4.setGeometry(QtCore.QRect(75, 70, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog_Permission_Allert)
        self.pushButton_OK_Error.clicked.connect(Dialog_Permission_Allert.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Permission_Allert)

    def retranslateUi(self, Dialog_Permission_Allert):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Permission_Allert.setWindowTitle(_translate("Dialog_Permission_Allert", "Allert"))
        Dialog_Permission_Allert.setWhatsThis(_translate("Dialog_Permission_Allert", "Non hai permessi a sufficienza per accedere alla seguente scheda. Chiedi ad un admin."))
        self.label_2.setText(_translate("Dialog_Permission_Allert", "PERMESSO NEGATO!"))
        self.label_3.setText(_translate("Dialog_Permission_Allert", "<html><head/><body><p><span style=\" font-size:11pt;\">Non hai i permessi per accedere</span></p></body></html>"))
        self.pushButton_OK_Error.setText(_translate("Dialog_Permission_Allert", "OK"))
        self.pushButton_OK_Error.setShortcut(_translate("Dialog_Permission_Allert", "Return"))
        self.label_4.setText(_translate("Dialog_Permission_Allert", "<html><head/><body><p align=\"center\">alla seguente scheda.</p></body></html>"))
import Resource_Error_rc
import Resource_logo_rc
